// src/lib/ui/waveform/waveform-bars.svelte
<script lang="ts">
  import { cn } from "$lib/utils/cn.js";
  import { levelToUnit } from "./waveform-model";

  /** Height of the flat line the bars grow out of, in px. */
  const BASELINE = 2;
  /** Total time for the growth to sweep from the first bar to the last. */
  const SWEEP_MS = 320;

  /**
   * The drawing only: a baseline, and bars growing upward from it, each an RMS level on a dB
   * scale. Colour comes from the caller (`currentColor`), so one instance serves the played and
   * the unplayed layer.
   */
  let {
    bars,
    height,
    grown,
    sweep,
    centered = false,
  }: {
    /** Resampled RMS levels, 0-255. Empty while the backend analyzes the file. */
    bars: readonly number[];
    height: number;
    /** False draws every bar flat on the baseline; flipping it to true grows them. */
    grown: boolean;
    /** Grow left to right instead of all at once. */
    sweep: boolean;
    /** Draw the baseline on the box's centre line instead of its bottom edge, for a bar that
     * never grows bars, so text beside it can share that centre line. */
    centered?: boolean;
  } = $props();
</script>

<div
  class={cn("absolute inset-x-0 bg-current", centered ? "top-1/2 -translate-y-1/2" : "bottom-0")}
  style:height="{BASELINE}px"
  data-slot="waveform-baseline"
></div>
{#if bars.length > 0}
  <svg
    class="absolute inset-0 size-full"
    viewBox="0 0 {bars.length} {height}"
    preserveAspectRatio="none"
    data-slot="waveform-bars"
  >
    <g fill="currentColor">
      {#each bars as level, index (index)}
        {@const barHeight = Math.max(BASELINE, levelToUnit(level) * (height - 2))}
        <rect
          class="transition-transform duration-300 ease-out"
          x={index + 0.15}
          y={height - barHeight}
          width={0.7}
          height={barHeight}
          style:transform-box="fill-box"
          style:transform-origin="50% 100%"
          style:transform="scaleY({grown ? 1 : BASELINE / barHeight})"
          style:transition-delay={sweep ? `${(index / bars.length) * SWEEP_MS}ms` : undefined}
        />
      {/each}
    </g>
  </svg>
{/if}

// src/renderer/shared/ui/waveform/waveform-bars.tsx
import { memo } from "react";
import { cn } from "@/renderer/shared/lib/utils";
import { levelToUnit } from "./waveform-model";

/** Height of the flat line the bars grow out of, in px. */
export const WAVEFORM_BASELINE = 2;

/** Total time for the growth to sweep from the first bar to the last. */
const SWEEP_MS = 320;

type WaveformBarsProps = {
  /** Resampled RMS levels, 0-255. Empty while the backend analyzes the file. */
  bars: readonly number[];
  height: number;
  /** False draws every bar flat on the baseline; flipping it to true grows them. */
  grown: boolean;
  /** Grow left to right instead of all at once. */
  sweep: boolean;
  /** Draw the baseline on the box's centre line instead of its bottom edge, for a bar that
   * never grows bars, so text beside it can share that centre line. */
  centered?: boolean;
};

/**
 * The drawing only: a baseline, and bars growing upward from it, each an RMS level on a dB scale.
 * Colour comes from the caller
 * (`currentColor`), so one instance serves the played and the unplayed layer. Memoised: the
 * seek bar re-renders with each position report, the bars only when they change.
 */
export const WaveformBars = memo(function WaveformBars({
  bars,
  height,
  grown,
  sweep,
  centered = false,
}: WaveformBarsProps) {
  return (
    <>
      <div
        className={cn(
          "absolute inset-x-0 bg-current",
          centered ? "top-1/2 -translate-y-1/2" : "bottom-0",
        )}
        style={{ height: WAVEFORM_BASELINE }}
        data-slot="waveform-baseline"
      />
      {bars.length > 0 ? (
        <svg
          className="absolute inset-0 size-full"
          viewBox={`0 0 ${bars.length} ${height}`}
          preserveAspectRatio="none"
          data-slot="waveform-bars"
        >
          <g fill="currentColor">
            {bars.map((level, index) => {
              const barHeight = Math.max(WAVEFORM_BASELINE, levelToUnit(level) * (height - 2));
              return (
                <rect
                  key={index}
                  className={cn("transition-transform duration-300 ease-out")}
                  x={index + 0.15}
                  y={height - barHeight}
                  width={0.7}
                  height={barHeight}
                  style={{
                    transformBox: "fill-box",
                    transformOrigin: "50% 100%",
                    transform: `scaleY(${grown ? 1 : WAVEFORM_BASELINE / barHeight})`,
                    transitionDelay: sweep ? `${(index / bars.length) * SWEEP_MS}ms` : undefined,
                  }}
                />
              );
            })}
          </g>
        </svg>
      ) : null}
    </>
  );
});
