// src/lib/ui/waveform/waveform-seek.svelte
<script lang="ts">
  import type { Attachment } from "svelte/attachments";
  import RollingNumber from "$lib/ui/rolling-number/rolling-number.svelte";
  import { cn } from "$lib/utils/cn.js";
  import { formatDuration } from "$lib/utils/format";
  import { createPointerSeek } from "./pointer-seek.svelte";
  import WaveformBars from "./waveform-bars.svelte";
  import { barCountForWidth, resampleBars } from "./waveform-model";

  type Span = { startMs: number; endMs: number };

  /**
   * The seek bar, shared by the dock and Now Playing at different `height`s (the same object,
   * scaled by context). Bars grow upward from a baseline; played is Ink-1 and unplayed is dimmer.
   * Its size never changes for a given caller, so geometry stays stable while the waveform
   * loads. Before analysis finishes it is a 2px line, and the bars grow out of that same line.
   *
   * The fill and playhead are drawn straight from the one playback clock into a CSS variable,
   * so this component does not re-run with time.
   */
  let {
    height,
    rms,
    showPlayhead = true,
    valueMs,
    durationMs,
    clock,
    retainClock,
    disabled,
    onInput,
    onCommit,
    activeSpan = null,
    hoveredLineSpan = null,
    onHoverPositionChange,
    sweepBars = false,
    lineOnly = false,
    playedClassName = "text-foreground",
    class: className,
  }: {
    /** Bar height in px. The dock uses a slim meter; Now Playing grows the same object larger. */
    height: number;
    /** RMS buckets 0-255, or null while the backend analyzes the file. */
    rms: readonly number[] | null;
    /** The playhead tick and hover guideline. Off for the dock's plain bar, where the fill edge
     * already marks the position and a second line would be redundant. */
    showPlayhead?: boolean;
    /** The position to print and to announce, in ms. Changes a few times a second. */
    valueMs: number;
    durationMs: number | null;
    /** The playback clock's position, in ms; moves every frame while playing. */
    clock: {
      get: () => number;
      subscribe: (listener: (ms: number) => void) => () => void;
    };
    /** Keeps the clock's frame loop running while the bar is shown. */
    retainClock: () => () => void;
    disabled: boolean;
    onInput: (positionMs: number) => void;
    onCommit: (positionMs: number) => void;
    /** The current lyric line's span, lit over the waveform. */
    activeSpan?: Span | null;
    /** The hovered lyric line's span, faintly marked over the waveform. */
    hoveredLineSpan?: Span | null;
    /** Reports the hovered position so Now Playing can faintly mark the corresponding line. */
    onHoverPositionChange?: (positionMs: number | null) => void;
    /** Bars grow from left to right when the waveform arrives, instead of all at once. */
    sweepBars?: boolean;
    /** A plain progress line with no bars (the dock): centred in its box. */
    lineOnly?: boolean;
    /** Colour class for the played part; the unplayed part is always dimmed ink. */
    playedClassName?: string;
    class?: string;
  } = $props();

  let width = $state(0);
  let grown = $state(false);
  const duration = $derived(durationMs ?? 0);
  const seekable = $derived(!disabled && duration > 0);
  const pointer = createPointerSeek(() => ({
    durationMs: duration,
    seekable,
    valueMs,
    onInput,
    onCommit,
    onHoverPositionChange,
  }));

  /**
   * Writes the played fraction to `--progress` from the clock. While dragging it follows the
   * pointer instead (`valueMs` is then the preview position).
   */
  const drive: Attachment<HTMLElement> = (node) => {
    const total = duration;
    const preview = pointer.dragging ? valueMs : null;
    const draw = (positionMs: number) => {
      const position = preview ?? positionMs;
      const progress = total > 0 ? Math.min(1, Math.max(0, position / total)) : 0;
      node.style.setProperty("--progress", String(progress));
    };
    draw(clock.get());
    const release = retainClock();
    const unsubscribe = clock.subscribe(draw);
    return () => {
      unsubscribe();
      release();
    };
  };

  const hasPeaks = $derived(rms !== null && rms.length > 0);
  // The bars mount flat on the baseline and grow one frame later, so the growth can transition.
  // A refined waveform for the same track swaps the bars in place without growing again; the
  // caller keys this component by track, so a new track starts flat.
  $effect(() => {
    if (!hasPeaks) return;
    const frame = requestAnimationFrame(() => (grown = true));
    return () => cancelAnimationFrame(frame);
  });

  const bars = $derived(rms === null ? [] : resampleBars(rms, barCountForWidth(width)));

  const spanStyle = (span: Span) =>
    duration > 0
      ? `left: ${(Math.max(0, span.startMs) / duration) * 100}%; width: ${(Math.min(duration, span.endMs - span.startMs) / duration) * 100}%`
      : undefined;
</script>

<div
  {@attach pointer.attach}
  {@attach drive}
  bind:clientWidth={width}
  role="slider"
  tabindex={seekable ? 0 : -1}
  aria-label="Playback position"
  aria-orientation="horizontal"
  aria-valuemin={0}
  aria-valuemax={duration}
  aria-valuenow={Math.min(valueMs, duration)}
  aria-valuetext="{formatDuration(valueMs)} of {formatDuration(durationMs)}"
  aria-disabled={!seekable}
  data-region="seek"
  data-ready={hasPeaks ? "true" : "false"}
  class={cn(
    "relative touch-none outline-none select-none focus-visible:ring-2 focus-visible:ring-ring",
    seekable ? "cursor-pointer" : "cursor-default opacity-60",
    className,
  )}
  style:height="{height}px"
>
  <div aria-hidden="true" class="absolute inset-0 text-foreground/35">
    <WaveformBars {bars} {height} {grown} sweep={sweepBars} centered={lineOnly} />
  </div>
  <div
    aria-hidden="true"
    class={cn("absolute inset-0", playedClassName)}
    style="clip-path: inset(0 calc((1 - var(--progress, 0)) * 100%) 0 0)"
  >
    <WaveformBars {bars} {height} {grown} sweep={sweepBars} centered={lineOnly} />
  </div>
  {#if activeSpan !== null}
    <div
      aria-hidden="true"
      data-slot="waveform-active-span"
      class="absolute inset-y-0 bg-foreground/15"
      style={spanStyle(activeSpan)}
    ></div>
  {/if}
  {#if hoveredLineSpan !== null}
    <div
      aria-hidden="true"
      data-slot="waveform-hovered-span"
      class="absolute inset-y-0 bg-foreground/10"
      style={spanStyle(hoveredLineSpan)}
    ></div>
  {/if}
  {#if showPlayhead && duration > 0}
    <div
      aria-hidden="true"
      class="absolute inset-y-0 w-px bg-foreground"
      style="left: calc(var(--progress, 0) * 100%)"
      data-slot="waveform-playhead"
    ></div>
  {/if}
  {#if seekable && pointer.hoverX !== null}
    {#if showPlayhead}
      <div
        aria-hidden="true"
        class="absolute inset-y-0 w-px bg-foreground/50"
        style:left="{pointer.hoverX}px"
      ></div>
    {/if}
    <span
      aria-hidden="true"
      data-slot="waveform-hover-time"
      class="pointer-events-none absolute bottom-full z-20 mb-1 -translate-x-1/2 rounded-sm bg-popover px-1.5 py-0.5 text-xs text-popover-foreground tabular-nums shadow-floating"
      style:left="{Math.min(width - 20, Math.max(20, pointer.hoverX))}px"
    >
      {#if pointer.dragging}
        {formatDuration(pointer.hoverMs)}
      {:else}
        <RollingNumber value={formatDuration(pointer.hoverMs)} />
      {/if}
    </span>
  {/if}
</div>

// src/renderer/shared/ui/waveform/waveform-seek.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { m, useMotionValue, useTransform, type MotionValue } from "motion/react";
import { cn } from "@/renderer/shared/lib/utils";
import { formatDuration } from "@/renderer/shared/lib/format";
import { RollingNumber } from "@/renderer/shared/ui/rolling-number";
import { WaveformBars } from "./waveform-bars";
import { usePointerSeek } from "./use-pointer-seek";
import { barCountForWidth, resampleBars } from "./waveform-model";

type WaveformSeekProps = {
  /** Bar height in px. The dock uses a slim meter; Now Playing grows the same object larger. */
  height: number;
  /** RMS buckets 0-255, or null while the backend analyzes the file. */
  rms: readonly number[] | null;
  /** The playhead tick and hover guideline. Off for the dock's plain bar, where the fill edge
   * already marks the position and a second line would be redundant. */
  showPlayhead?: boolean;
  /** The position to print and to announce, in ms. Changes a few times a second. */
  valueMs: number;
  durationMs: number | null;
  /**
   * The position to draw, in ms: a motion value that moves every frame while playing (the
   * playback clock), so the fill and playhead advance without this component re-rendering.
   */
  position: MotionValue<number>;
  disabled: boolean;
  onInput: (positionMs: number) => void;
  onCommit: (positionMs: number) => void;
  /** The current lyric line's span, lit over the waveform. */
  activeSpan?: { startMs: number; endMs: number } | null;
  /** The hovered lyric line's span, faintly marked over the waveform. */
  hoveredLineSpan?: { startMs: number; endMs: number } | null;
  /** Reports the hovered position so Now Playing can faintly mark the corresponding line. */
  onHoverPositionChange?: (positionMs: number | null) => void;
  /** Bars grow from left to right when the waveform arrives, instead of all at once. */
  sweepBars?: boolean;
  /** A plain progress line with no bars (the dock): centred in its box. */
  lineOnly?: boolean;
  /** Colour class for the played part; the unplayed part is always dimmed ink. */
  playedClassName?: string;
  className?: string;
};

/**
 * The seek bar, shared by the dock and Now Playing at different `height`s (the same object,
 * scaled by context). Bars grow upward from a baseline; played is Ink-1 and unplayed is dimmer.
 * Its size never changes for a given caller, so geometry stays stable while the waveform
 * loads. Before analysis finishes it is a 2px line, and the bars grow out of that same line.
 */
export function WaveformSeek({
  height,
  rms,
  showPlayhead = true,
  valueMs,
  durationMs,
  position: clock,
  disabled,
  onInput,
  onCommit,
  activeSpan = null,
  hoveredLineSpan = null,
  onHoverPositionChange,
  sweepBars = false,
  lineOnly = false,
  playedClassName = "text-foreground",
  className,
}: WaveformSeekProps) {
  const ref = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(0);
  const [grown, setGrown] = useState(false);
  const duration = durationMs ?? 0;
  const seekable = !disabled && duration > 0;
  const pointer = usePointerSeek({
    ref,
    durationMs: duration,
    width,
    seekable,
    valueMs,
    onInput,
    onCommit,
    onHoverPositionChange,
  });

  // Fill and playhead follow `clock`, bound to styles so this does not re-render every frame.
  // While dragging they follow the pointer instead (`valueMs` is then the preview position).
  const preview = useMotionValue(valueMs);
  useEffect(() => preview.set(valueMs), [preview, valueMs]);
  const dragging = pointer.dragging;
  const progress = useTransform(() => {
    const position = dragging ? preview.get() : clock.get();
    return duration > 0 ? Math.min(1, Math.max(0, position / duration)) : 0;
  });
  const clipPath = useTransform(() => `inset(0 ${(1 - progress.get()) * 100}% 0 0)`);
  const playheadLeft = useTransform(() => `${progress.get() * 100}%`);

  useEffect(() => {
    const element = ref.current;
    if (element === null) return;
    const observer = new ResizeObserver(([entry]) => {
      if (entry) setWidth(entry.contentRect.width);
    });
    observer.observe(element);
    setWidth(element.getBoundingClientRect().width);
    return () => observer.disconnect();
  }, []);

  const hasPeaks = rms !== null && rms.length > 0;
  // The bars mount flat on the baseline and grow one frame later, so the growth can transition.
  // A refined waveform for the same track swaps the bars in place without growing again; the
  // caller keys this component by track, so a new track starts flat.
  useEffect(() => {
    if (!hasPeaks) return;
    const frame = requestAnimationFrame(() => setGrown(true));
    return () => cancelAnimationFrame(frame);
  }, [hasPeaks]);

  const bars = useMemo(
    () => (rms === null ? [] : resampleBars(rms, barCountForWidth(width))),
    [rms, width],
  );

  const spanStyle = (span: { startMs: number; endMs: number }) =>
    duration > 0
      ? {
          left: `${(Math.max(0, span.startMs) / duration) * 100}%`,
          width: `${(Math.min(duration, span.endMs - span.startMs) / duration) * 100}%`,
        }
      : undefined;

  return (
    <div
      ref={ref}
      role="slider"
      tabIndex={seekable ? 0 : -1}
      aria-label="Playback position"
      aria-orientation="horizontal"
      aria-valuemin={0}
      aria-valuemax={duration}
      aria-valuenow={Math.min(valueMs, duration)}
      aria-valuetext={`${formatDuration(valueMs)} of ${formatDuration(durationMs)}`}
      aria-disabled={!seekable}
      data-region="seek"
      data-ready={hasPeaks ? "true" : "false"}
      className={cn(
        "relative touch-none select-none outline-none focus-visible:ring-2 focus-visible:ring-ring",
        seekable ? "cursor-pointer" : "cursor-default opacity-60",
        className,
      )}
      style={{ height }}
      {...pointer.handlers}
    >
      <div aria-hidden="true" className="absolute inset-0 text-foreground/35">
        <WaveformBars
          bars={bars}
          height={height}
          grown={grown}
          sweep={sweepBars}
          centered={lineOnly}
        />
      </div>
      <m.div
        aria-hidden="true"
        className={cn("absolute inset-0", playedClassName)}
        style={{ clipPath }}
      >
        <WaveformBars
          bars={bars}
          height={height}
          grown={grown}
          sweep={sweepBars}
          centered={lineOnly}
        />
      </m.div>
      {activeSpan !== null ? (
        <div
          aria-hidden="true"
          data-slot="waveform-active-span"
          className="absolute inset-y-0 bg-foreground/15"
          style={spanStyle(activeSpan)}
        />
      ) : null}
      {hoveredLineSpan !== null ? (
        <div
          aria-hidden="true"
          data-slot="waveform-hovered-span"
          className="absolute inset-y-0 bg-foreground/10"
          style={spanStyle(hoveredLineSpan)}
        />
      ) : null}
      {showPlayhead && duration > 0 ? (
        <m.div
          aria-hidden="true"
          className="absolute inset-y-0 w-px bg-foreground"
          style={{ left: playheadLeft }}
          data-slot="waveform-playhead"
        />
      ) : null}
      {seekable && pointer.hoverX !== null ? (
        <>
          {showPlayhead ? (
            <div
              aria-hidden="true"
              className="absolute inset-y-0 w-px bg-foreground/50"
              style={{ left: pointer.hoverX }}
            />
          ) : null}
          <span
            aria-hidden="true"
            data-slot="waveform-hover-time"
            className="pointer-events-none absolute bottom-full z-20 mb-1 -translate-x-1/2 rounded-sm bg-popover px-1.5 py-0.5 text-xs tabular-nums text-popover-foreground shadow-floating"
            style={{ left: Math.min(width - 20, Math.max(20, pointer.hoverX)) }}
          >
            {pointer.dragging ? (
              formatDuration(pointer.hoverMs)
            ) : (
              <RollingNumber value={formatDuration(pointer.hoverMs)} />
            )}
          </span>
        </>
      ) : null}
    </div>
  );
}
