// src/lib/components/track-table/track-table.svelte
<script lang="ts">
  import { Root as ContextMenuRoot, Trigger as ContextMenuTrigger } from "$lib/ui/context-menu";
  import { goto } from "$app/navigation";
  import { isFilePresent, isTrackAvailable, trackLinks } from "$lib/library/tracks";
  import type { LibrarySortDirection, LibraryTrackSortKey } from "$lib/native";
  import { requireNative } from "$lib/native";
  import { getPlayback } from "$lib/playback/context";
  import ContextMenuContent from "$lib/ui/context-menu/context-menu-content.svelte";
  import ContextMenuItem from "$lib/ui/context-menu/context-menu-item.svelte";
  import {
    TableBody,
    TableCaption,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
  } from "$lib/ui/shadcn/table";
  import { cn } from "$lib/utils/cn.js";
  import { createVirtualRows } from "$lib/ui/virtual-rows.svelte";
  import {
    columnText,
    albumTrackColumns,
    libraryTrackColumns,
    hasSeveralDiscs,
    startsDisc,
    trackRowState,
    trackTableBreakpoints,
    TRACK_ROW_HEIGHT,
    type TrackColumn,
    type TrackTableLayout,
    type TrackTableRow,
  } from "./track-columns";
  import TrackActionCell from "./track-action-cell.svelte";
  import TrackPropertiesSheet from "./track-properties-sheet.svelte";
  import TrackSortHeader from "./track-sort-header.svelte";

  let {
    rows,
    caption,
    layout = "library",
    scrollElement,
    ontopindexchange,
    sortKey,
    sortDirection = "ascending",
    onsortchange,
    onplaytrack,
  }: {
    rows: readonly TrackTableRow[];
    caption: string;
    layout?: TrackTableLayout;
    /**
     * The region the table scrolls in to virtualize its rows against (`null` while it is still
     * mounting). Omit it to render every row.
     */
    scrollElement?: HTMLElement | null;
    /** Told the index of the first row in view, for the scroll index label. */
    ontopindexchange?: (index: number) => void;
    sortKey?: LibraryTrackSortKey;
    sortDirection?: LibrarySortDirection;
    onsortchange?: (key: LibraryTrackSortKey, direction: LibrarySortDirection) => void;
    /** Starts playback of this track in the page's context; pause and resume go straight to playback. */
    onplaytrack: (id: string) => void;
  } = $props();

  const columns = $derived(layout === "library" ? libraryTrackColumns : albumTrackColumns);
  const virtualized = $derived(scrollElement !== undefined);
  const playback = getPlayback();

  let propertiesFor = $state<string | null>(null);
  let menuRow = $state<TrackTableRow | null>(null);
  let container = $state<HTMLElement | null>(null);
  let body = $state<HTMLElement | null>(null);

  const virtual = createVirtualRows({
    count: () => rows.length,
    scrollElement: () => scrollElement ?? null,
    rowHeight: TRACK_ROW_HEIGHT,
    overscan: 10,
    container: () => container,
    body: () => body,
  });
  $effect(() => {
    if (virtualized) ontopindexchange?.(virtual.topIndex);
  });

  const visibleIndexes = $derived(
    virtualized ? virtual.items.map((item) => item.index) : rows.map((_, index) => index),
  );
  const topSpacer = $derived(virtualized ? virtual.topSpacer : 0);
  const bottomSpacer = $derived(virtualized ? virtual.bottomSpacer : 0);
  // An album on several discs is split by a "Disc n" row. Only in the plain (unvirtualized)
  // album layout, where every row has the same height.
  const splitsDiscs = $derived(!virtualized && layout === "album" && hasSeveralDiscs(rows));

  /** Width (for `<col>` only) and breakpoint visibility from one column definition. */
  function columnClass(column: TrackColumn, withWidth = false) {
    return cn(
      withWidth && column.width,
      column.hideBelow && trackTableBreakpoints[column.hideBelow].hide,
    );
  }

  function isInteractiveTarget(event: MouseEvent) {
    const target = event.target;
    return (
      target instanceof Element &&
      target.closest("button, a, input, select, textarea, [role='button'], [data-row-action]") !==
        null
    );
  }

  function activateRow(event: MouseEvent, row: TrackTableRow, intent: "play" | "resume" | null) {
    if (isInteractiveTarget(event)) return;
    if (intent === "play") onplaytrack(row.id);
    else if (intent === "resume") void playback.resume();
  }

  /** Resolves the row under a right-click; the spacer rows have none, so no menu opens there. */
  function selectMenuRow(event: MouseEvent) {
    const target = event.target;
    const id =
      target instanceof Element
        ? (target.closest<HTMLElement>("tr[data-row-id]")?.dataset.rowId ?? null)
        : null;
    const row = id === null ? undefined : rows.find((candidate) => candidate.id === id);
    if (row) menuRow = row;
    else event.stopPropagation();
  }

  // Plain strings from routes.ts, not resolve(): see there.
  function goTo(href: string) {
    void goto(href);
  }
</script>

<div bind:this={container} class="@container/track-table min-w-0">
  <!-- Not the shadcn Table root: its overflow wrapper would break the sticky header. -->
  <table class="w-full table-fixed border-collapse text-sm">
    <colgroup>
      {#each columns as column (column.id)}
        <col class={columnClass(column, true)} />
      {/each}
    </colgroup>
    <TableCaption class="sr-only">{caption}</TableCaption>
    <TableHeader class="acrylic sticky top-0 z-10 text-left text-muted-foreground">
      <TableRow class="h-9 border-b border-border">
        {#each columns as column (column.id)}
          {@const key = layout === "library" ? column.sortKey : undefined}
          {@const active = key !== undefined && key === sortKey}
          <TableHead
            scope="col"
            data-column-id={column.id}
            class={cn("px-3 font-medium last:text-right", columnClass(column))}
            aria-sort={active ? sortDirection : undefined}
          >
            {#if key !== undefined && onsortchange}
              <TrackSortHeader
                header={column.header}
                sortKey={key}
                {active}
                direction={sortDirection}
                {onsortchange}
              />
            {:else}
              {column.header}
            {/if}
          </TableHead>
        {/each}
      </TableRow>
    </TableHeader>
    <ContextMenuRoot>
      <ContextMenuTrigger>
        {#snippet child({ props })}
          <TableBody {...props} bind:ref={body} oncontextmenucapture={selectMenuRow}>
            <!-- Spacer heights must jump, never animate: the reduced-motion rule gives every element a
           transition, and a lagging spacer puts the rows in the wrong place. -->
            {#if topSpacer > 0}
              <tr aria-hidden="true">
                <td colspan={columns.length} class="p-0"
                  ><div class="transition-none" style:height="{topSpacer}px"></div></td
                >
              </tr>
            {/if}
            {#each visibleIndexes as index (rows[index]?.id ?? index)}
              {@const row = rows[index]}
              {#if row}
                {#if splitsDiscs && startsDisc(rows, index)}
                  <TableRow class="border-b border-border/70">
                    <TableCell
                      colspan={columns.length}
                      class="px-3 pt-6 pb-2 text-sm text-muted-foreground"
                    >
                      Disc {row.discNumber}
                    </TableCell>
                  </TableRow>
                {/if}
                {@const { action, clickIntent, playbackState } = trackRowState(
                  row,
                  playback.activeTrackId,
                  playback.status,
                )}
                {@const available = isTrackAvailable(row)}
                {@const runAction = {
                  play: () => onplaytrack(row.id),
                  pause: () => void playback.pause(),
                  resume: () => void playback.resume(),
                }[action.kind]}
                <!-- Clicking the row is a pointer shortcut; the action button is the keyboard path. -->
                <tr
                  data-row-id={row.id}
                  data-playback-state={playbackState}
                  data-availability={row.availability}
                  style:height="{TRACK_ROW_HEIGHT}px"
                  class={cn(
                    "group/track border-b border-border/70 text-foreground outline-none transition-colors hover:bg-accent/40 has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-inset has-[:focus-visible]:ring-ring",
                    clickIntent !== null && "cursor-pointer",
                  )}
                  onclick={(event) => activateRow(event, row, clickIntent)}
                >
                  {#each columns as column (column.id)}
                    <TableCell
                      data-column-id={column.id}
                      class={cn(
                        "truncate px-3 py-0 last:text-right tabular-nums",
                        columnClass(column),
                      )}
                    >
                      {#if column.kind === "action"}
                        <TrackActionCell {row} {action} {available} {layout} run={runAction} />
                      {:else if column.kind === "title"}
                        <div class="min-w-0 text-left">
                          <div class="flex min-w-0 items-center gap-2">
                            <span class="truncate" title={row.title}>{row.title}</span>
                            {#if row.availability === "missing"}
                              <span class="shrink-0 text-sm text-muted-foreground">Missing</span>
                            {/if}
                          </div>
                          {#if layout === "album" && row.artist}
                            <span
                              class={cn(
                                "mt-0.5 hidden truncate text-sm text-muted-foreground",
                                trackTableBreakpoints.compact.show,
                              )}
                              title={row.artist}>{row.artist}</span
                            >
                          {/if}
                        </div>
                      {:else if column.kind === "text"}
                        {@const text = columnText(column, row)}
                        <span title={text}>{text}</span>
                      {/if}
                    </TableCell>
                  {/each}
                </tr>
              {/if}
            {/each}
            {#if bottomSpacer > 0}
              <tr aria-hidden="true">
                <td colspan={columns.length} class="p-0"
                  ><div class="transition-none" style:height="{bottomSpacer}px"></div></td
                >
              </tr>
            {/if}
          </TableBody>
        {/snippet}
      </ContextMenuTrigger>
      <ContextMenuContent>
        {#if menuRow}
          {@const row = menuRow}
          {#if isTrackAvailable(row)}
            <ContextMenuItem onSelect={() => void playback.enqueueTrack(row.id, true)}>
              Play next
            </ContextMenuItem>
            <ContextMenuItem onSelect={() => void playback.enqueueTrack(row.id, false)}>
              Add to queue
            </ContextMenuItem>
          {/if}
          {#if layout === "library"}
            {@const links = trackLinks(row)}
            {#if links.album?.href}
              {@const href = links.album.href}
              <ContextMenuItem onSelect={() => goTo(href)}>Go to album</ContextMenuItem>
            {/if}
            {#if links.artist?.href}
              {@const href = links.artist.href}
              <ContextMenuItem onSelect={() => goTo(href)}>Go to artist</ContextMenuItem>
            {/if}
          {/if}
          {#if isFilePresent(row)}
            <ContextMenuItem onSelect={() => void requireNative().revealLibraryTrack(row.id)}>
              Show in Explorer
            </ContextMenuItem>
          {/if}
          <ContextMenuItem onSelect={() => (propertiesFor = row.id)}>Properties</ContextMenuItem>
        {/if}
      </ContextMenuContent>
    </ContextMenuRoot>
  </table>
  <TrackPropertiesSheet trackId={propertiesFor} onclose={() => (propertiesFor = null)} />
</div>

// src/renderer/widgets/track-table/track-table.tsx
import { Fragment, useEffect, useMemo, useState, type MouseEvent } from "react";
import { useNavigate } from "@tanstack/react-router";
import { flexRender, getCoreRowModel, useReactTable, type ColumnMeta } from "@tanstack/react-table";
import { useVirtualizer } from "@tanstack/react-virtual";
import { ArrowDown, ArrowUp } from "lucide-react";
import {
  toggleSortDirection,
  toNameSegment,
  trackSortLabels,
  type LibrarySortDirection,
  type LibraryTrackSortKey,
} from "@/renderer/entities/library";
import { usePlaybackActions } from "@/renderer/entities/playback";
import { cn } from "@/renderer/shared/lib/utils";
import { nativeApi } from "@/renderer/shared/lib/native";
import { ContextMenu, ContextMenuTrigger, MenuContent, MenuItem } from "@/renderer/shared/ui/menu";
import { Button } from "@/renderer/shared/ui/shadcn/button";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/renderer/shared/ui/shadcn/table";
import { TRACK_ROW_HEIGHT, trackTableBreakpoints } from "./breakpoints";
import { albumTrackColumns, libraryTrackColumns } from "./track-columns";
import { TrackPropertiesSheet } from "./track-properties-sheet";
import { TrackTableContext, type TrackTableController } from "./track-table-context";
import type { TrackPlaybackStatus, TrackTableLayout, TrackTableRow } from "./types";

type TrackTableProps = {
  rows: TrackTableRow[];
  layout: TrackTableLayout;
  caption: string;
  activeTrackId?: string | null;
  playbackStatus?: TrackPlaybackStatus;
  sortKey?: LibraryTrackSortKey;
  sortDirection?: LibrarySortDirection;
  /**
   * The scroll element to virtualize rows against, or `null` while it is still mounting.
   * Omit it to render every row.
   */
  scrollElement?: HTMLElement | null;
  initialOffset?: number;
  /** Told the index of the first row in view, for the scroll index label. */
  onTopIndexChange?: (index: number) => void;
  onSortChange?: (key: LibraryTrackSortKey, direction: LibrarySortDirection) => void;
  onPlayTrack: (id: string) => void;
  onPauseActive?: () => void;
  onResumeActive?: () => void;
};

export function TrackTable({
  rows,
  layout,
  caption,
  activeTrackId = null,
  playbackStatus = "stopped",
  sortKey,
  sortDirection = "ascending",
  scrollElement,
  initialOffset,
  onTopIndexChange,
  onSortChange,
  onPlayTrack,
  onPauseActive,
  onResumeActive,
}: TrackTableProps) {
  const { enqueueTrack } = usePlaybackActions();
  const navigate = useNavigate();
  const [propertiesFor, setPropertiesFor] = useState<string | null>(null);
  const controller = useMemo<TrackTableController>(
    () => ({
      layout,
      activeTrackId,
      playbackStatus,
      onPlayTrack,
      onPauseActive,
      onResumeActive,
    }),
    [activeTrackId, layout, onPauseActive, onPlayTrack, onResumeActive, playbackStatus],
  );
  const table = useReactTable({
    data: rows,
    columns: layout === "library" ? libraryTrackColumns : albumTrackColumns,
    getCoreRowModel: getCoreRowModel(),
  });
  const allRows = table.getRowModel().rows;
  const virtualized = scrollElement !== undefined;
  const virtualizer = useVirtualizer({
    count: virtualized ? allRows.length : 0,
    getScrollElement: () => scrollElement ?? null,
    estimateSize: () => TRACK_ROW_HEIGHT,
    overscan: 10,
    initialOffset,
  });
  const virtualRows = virtualized ? virtualizer.getVirtualItems() : [];
  const topIndex = virtualizer.range?.startIndex ?? 0;
  useEffect(() => {
    if (virtualized) onTopIndexChange?.(topIndex);
  }, [virtualized, topIndex, onTopIndexChange]);
  const visibleRows = virtualized ? virtualRows.map((item) => allRows[item.index]!) : allRows;
  const topSpacer = virtualized ? (virtualRows[0]?.start ?? 0) : 0;
  const bottomSpacer = virtualized
    ? virtualizer.getTotalSize() - (virtualRows.at(-1)?.end ?? 0)
    : 0;
  const columnCount = table.getVisibleLeafColumns().length;
  // An album on several discs is split by a "Disc n" row. Only in the plain (unvirtualized)
  // album layout, where every row has the same height.
  const multiDisc = !virtualized && layout === "album" && rows.some((r) => (r.discNumber ?? 1) > 1);

  return (
    <TrackTableContext value={controller}>
      <div className="@container/track-table min-w-0">
        <Table className="w-full table-fixed border-collapse text-sm">
          <colgroup>
            {table.getVisibleLeafColumns().map((column) => (
              <col key={column.id} className={columnClassName(column.columnDef.meta, true)} />
            ))}
          </colgroup>
          <TableCaption className="sr-only">{caption}</TableCaption>
          <TableHeader className="acrylic sticky top-0 z-10 text-left text-muted-foreground">
            {table.getHeaderGroups().map((group) => (
              <TableRow key={group.id} className="h-9 border-b border-border">
                {group.headers.map((header) => {
                  const meta = header.column.columnDef.meta;
                  const key = layout === "library" ? meta?.sortKey : undefined;
                  const active = key !== undefined && key === sortKey;
                  return (
                    <TableHead
                      key={header.id}
                      scope="col"
                      data-column-id={header.column.id}
                      className={cn("px-3 font-medium last:text-right", columnClassName(meta))}
                      aria-sort={active ? sortDirection : undefined}
                    >
                      {key && onSortChange ? (
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          className="-mx-2 h-8 px-2 text-sm"
                          aria-label={`Sort by ${trackSortLabels[key]}`}
                          onClick={() =>
                            onSortChange(
                              key,
                              active ? toggleSortDirection(sortDirection) : "ascending",
                            )
                          }
                        >
                          <span>
                            {flexRender(header.column.columnDef.header, header.getContext())}
                          </span>
                          {active ? (
                            sortDirection === "ascending" ? (
                              <ArrowUp aria-hidden="true" />
                            ) : (
                              <ArrowDown aria-hidden="true" />
                            )
                          ) : null}
                        </Button>
                      ) : (
                        flexRender(header.column.columnDef.header, header.getContext())
                      )}
                    </TableHead>
                  );
                })}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {topSpacer > 0 ? <SpacerRow height={topSpacer} columns={columnCount} /> : null}
            {visibleRows.map((row) => {
              const original = row.original;
              const active = original.id === activeTrackId;
              const rowActionAvailable =
                original.playable &&
                original.availability === "available" &&
                (!active || playbackStatus !== "playing");
              const queueable = original.playable && original.availability === "available";
              const previousDisc = allRows[row.index - 1]?.original.discNumber;
              const discHeader =
                multiDisc && original.discNumber != null && original.discNumber !== previousDisc;
              return (
                <Fragment key={row.id}>
                  {discHeader ? (
                    <TableRow className="border-b border-border/70">
                      <TableCell
                        colSpan={columnCount}
                        className="px-3 pt-6 pb-2 text-sm text-muted-foreground"
                      >
                        Disc {original.discNumber}
                      </TableCell>
                    </TableRow>
                  ) : null}
                  <ContextMenu>
                    <ContextMenuTrigger
                      render={
                        <TableRow
                          data-playback-state={
                            active && (playbackStatus === "playing" || playbackStatus === "paused")
                              ? playbackStatus
                              : undefined
                          }
                          data-availability={original.availability}
                          style={{ height: TRACK_ROW_HEIGHT }}
                          className={cn(
                            "group/track border-b border-border/70 text-foreground outline-none transition-colors hover:bg-accent/40 has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-inset has-[:focus-visible]:ring-ring",
                            rowActionAvailable && "cursor-pointer",
                          )}
                          onClick={(event) => {
                            if (isInteractiveTarget(event)) return;
                            activateRow(
                              original,
                              active,
                              playbackStatus,
                              onPlayTrack,
                              onResumeActive,
                            );
                          }}
                        />
                      }
                    >
                      {row.getVisibleCells().map((cell) => (
                        <TableCell
                          key={cell.id}
                          data-column-id={cell.column.id}
                          className={cn(
                            "truncate px-3 last:text-right tabular-nums",
                            columnClassName(cell.column.columnDef.meta),
                          )}
                        >
                          {flexRender(cell.column.columnDef.cell, cell.getContext())}
                        </TableCell>
                      ))}
                    </ContextMenuTrigger>
                    <MenuContent side="bottom" align="start" className="min-w-44">
                      {queueable ? (
                        <>
                          <MenuItem onClick={() => void enqueueTrack(original.id, true)}>
                            Play next
                          </MenuItem>
                          <MenuItem onClick={() => void enqueueTrack(original.id, false)}>
                            Add to queue
                          </MenuItem>
                        </>
                      ) : null}
                      {layout === "library" && original.album ? (
                        <MenuItem
                          onClick={() =>
                            void navigate({
                              to: "/library/albums/$albumArtist/$albumTitle",
                              params: {
                                albumArtist: toNameSegment(albumArtistOf(original)),
                                albumTitle: toNameSegment(original.album!.trim()),
                              },
                            })
                          }
                        >
                          Go to album
                        </MenuItem>
                      ) : null}
                      {layout === "library" && albumArtistOf(original) !== "" ? (
                        <MenuItem
                          onClick={() =>
                            void navigate({
                              to: "/library/album-artists/$artistName",
                              params: { artistName: toNameSegment(albumArtistOf(original)) },
                            })
                          }
                        >
                          Go to artist
                        </MenuItem>
                      ) : null}
                      {original.availability === "available" ? (
                        <MenuItem onClick={() => void nativeApi().revealLibraryTrack(original.id)}>
                          Show in Explorer
                        </MenuItem>
                      ) : null}
                      <MenuItem onClick={() => setPropertiesFor(original.id)}>Properties</MenuItem>
                    </MenuContent>
                  </ContextMenu>
                </Fragment>
              );
            })}
            {bottomSpacer > 0 ? <SpacerRow height={bottomSpacer} columns={columnCount} /> : null}
          </TableBody>
        </Table>
        <TrackPropertiesSheet trackId={propertiesFor} onClose={() => setPropertiesFor(null)} />
      </div>
    </TrackTableContext>
  );
}

/** The artist the library groups the track under: album artist, else artist. */
function albumArtistOf(row: TrackTableRow) {
  return row.albumArtist?.trim() || row.artist?.trim() || "";
}

/** Width (for `<col>` only) and breakpoint visibility from one column definition. */
function columnClassName(meta: ColumnMeta<TrackTableRow, unknown> | undefined, withWidth = false) {
  return cn(
    withWidth && meta?.width,
    meta?.hideBelow && trackTableBreakpoints[meta.hideBelow].hide,
  );
}

function SpacerRow({ height, columns }: { height: number; columns: number }) {
  return (
    <TableRow aria-hidden="true" style={{ height }}>
      <TableCell colSpan={columns} className="p-0" />
    </TableRow>
  );
}

function activateRow(
  row: TrackTableRow,
  active: boolean,
  playbackStatus: TrackPlaybackStatus,
  onPlayTrack: (id: string) => void,
  onResumeActive?: () => void,
) {
  if (!row.playable || row.availability !== "available") return;
  if (active && playbackStatus === "playing") return;
  if (active && playbackStatus === "paused") {
    onResumeActive?.();
    return;
  }
  onPlayTrack(row.id);
}

function isInteractiveTarget(event: MouseEvent<HTMLTableRowElement>) {
  const target = event.target;
  return (
    target instanceof Element &&
    target.closest("button, a, input, select, textarea, [role='button'], [data-row-action]") !==
      null
  );
}
