// src/lib/components/dock/dock-identity.svelte
<script lang="ts">
  import { ContextMenu as ContextMenuPrimitive } from "bits-ui";
  import { ChevronDown } from "@lucide/svelte";
  import { goto } from "$app/navigation";
  import { albumArtistHref, albumHref } from "$lib/library/routes";
  import { getPlayback } from "$lib/playback/context";
  import { nowPlaying } from "$lib/shell/now-playing.svelte";
  import Artwork from "$lib/ui/artwork.svelte";
  import ContextMenuContent from "$lib/ui/context-menu/context-menu-content.svelte";
  import ContextMenuItem from "$lib/ui/context-menu/context-menu-item.svelte";
  import { motionFor } from "$lib/ui/motion/svelte-motion";
  import { Button } from "$lib/ui/shadcn/button";
  import * as Tooltip from "$lib/ui/shadcn/tooltip";
  import { prefersReducedMotion } from "svelte/motion";
  import type { TransitionConfig } from "svelte/transition";

  /** Sliding distance for the artwork, title and artist. One value so they travel together. */
  const SLIDE_PX = 16;

  const playback = getPlayback();
  const item = $derived(playback.item);
  const trackKey = $derived(item?.file.path ?? "none");
  const title = $derived(item?.title ?? "Nothing playing");
  const nowPlayingOpen = $derived(nowPlaying.isOpen);
  const hasTrack = $derived(item !== null);
  const albumKey = $derived(item?.albumKey ?? null);
  const artistName = $derived(
    albumKey?.albumArtist || item?.albumArtist?.trim() || item?.artist?.trim() || "",
  );

  /**
   * Next enters from the right and pushes the old track out to the left; previous mirrors it.
   * Under reduced motion it is a plain crossfade.
   */
  function slide(_node: Element, { entering }: { entering: boolean }): TransitionConfig {
    const reduced = prefersReducedMotion.current;
    const { duration, easing } = motionFor("mediumMove", reduced);
    const direction = playback.lastNavigation === "previous" ? -1 : 1;
    const x = reduced ? 0 : (entering ? direction : -direction) * SLIDE_PX;
    return {
      duration,
      easing,
      css: (t, u) => `transform: translateX(${x * u}px); opacity: ${t}`,
    };
  }

  // Plain strings from routes.ts, not resolve(): see there.
  function goToAlbum() {
    if (albumKey === null) return;
    // eslint-disable-next-line svelte/no-navigation-without-resolve
    void goto(albumHref(albumKey.albumArtist, albumKey.title));
  }

  function goToArtist() {
    // eslint-disable-next-line svelte/no-navigation-without-resolve
    void goto(albumArtistHref(artistName));
  }

  let errorTooltipOpen = $state(false);
</script>

<div class="col-start-1 flex min-w-0 items-center gap-3" data-region="playback-identity">
  <!-- Now Playing has its own big Sleeve (the shared-element target). While it is open this slot
  holds the close affordance instead, so the dock's layout does not shift. -->
  {#if nowPlayingOpen}
    <Button
      variant="ghost"
      aria-label="Close Now Playing"
      onclick={() => nowPlaying.close()}
      data-slot="sleeve-close"
      class="size-16 shrink-0"
    >
      <ChevronDown aria-hidden="true" class="size-6" />
    </Button>
  {:else}
    <ContextMenuPrimitive.Root>
      <ContextMenuPrimitive.Trigger>
        {#snippet child({ props })}
          <!-- Inset, not edge-filling: a rounded tile that sits inside the identity column like
          any other artwork placed in the workspace. -->
          <button
            {...props}
            type="button"
            aria-label="Open Now Playing"
            disabled={!hasTrack}
            onclick={() => nowPlaying.open()}
            data-slot="sleeve"
            class="grid aspect-square size-16 shrink-0 cursor-pointer overflow-hidden rounded-lg outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default"
          >
            {#key trackKey}
              <span
                class="size-full [grid-area:1/1]"
                in:slide={{ entering: true }}
                out:slide={{ entering: false }}
              >
                <Artwork
                  artwork={item?.artwork ?? null}
                  alt={item === null ? "" : `${item.title} artwork`}
                  loading="eager"
                  class="size-full rounded-lg"
                />
              </span>
            {/key}
          </button>
        {/snippet}
      </ContextMenuPrimitive.Trigger>
      {#if hasTrack}
        <ContextMenuContent side="right" align="start" class="min-w-40">
          {#if albumKey !== null}
            <ContextMenuItem onSelect={goToAlbum}>Go to album</ContextMenuItem>
          {/if}
          {#if artistName !== ""}
            <ContextMenuItem onSelect={goToArtist}>Go to artist</ContextMenuItem>
          {/if}
        </ContextMenuContent>
      {/if}
    </ContextMenuPrimitive.Root>
    <div class="grid min-w-0">
      <!-- Title and artist are one keyed block, so they leave and arrive as one piece. -->
      {#key trackKey}
        <div
          class="flex min-w-0 flex-col justify-center gap-0.5 [grid-area:1/1]"
          in:slide={{ entering: true }}
          out:slide={{ entering: false }}
        >
          <button
            type="button"
            disabled={item === null}
            onclick={() => nowPlaying.toggle()}
            {title}
            class="block max-w-full cursor-pointer truncate rounded-sm text-left text-sm font-medium text-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default"
          >
            {title}
          </button>
          {#if playback.transport.commandError}
            <Tooltip.Root bind:open={errorTooltipOpen}>
              <Tooltip.Trigger>
                {#snippet child({ props })}
                  <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
                  <span
                    {...props}
                    class="block truncate text-sm text-destructive"
                    role="alert"
                    tabindex="0"
                    onfocus={() => (errorTooltipOpen = true)}
                    onblur={() => (errorTooltipOpen = false)}
                  >
                    {playback.transport.commandError}
                  </span>
                {/snippet}
              </Tooltip.Trigger>
              <Tooltip.Content>{playback.transport.commandError}</Tooltip.Content>
            </Tooltip.Root>
          {:else if item?.artist}
            <span class="block truncate text-sm text-muted-foreground" title={item.artist}>
              {item.artist}
            </span>
          {/if}
        </div>
      {/key}
    </div>
  {/if}
</div>

// src/renderer/widgets/playback-region/ui/dock-identity.tsx
import { useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { AnimatePresence, m, type Variants } from "motion/react";
import { ChevronDown } from "lucide-react";
import { toNameSegment } from "@/renderer/entities/library";
import { usePlaybackNavigation, usePlaybackTransport } from "@/renderer/entities/playback";
import {
  NOW_PLAYING_SLEEVE_ID,
  SLEEVE_RADIUS_PX,
  useNowPlaying,
} from "@/renderer/features/now-playing-transition";
import type { PlaybackItem } from "@/shared/ipc";
import { cn } from "@/renderer/shared/lib/utils";
import { Artwork } from "@/renderer/shared/ui/artwork";
import { ContextMenu, ContextMenuTrigger, MenuContent, MenuItem } from "@/renderer/shared/ui/menu";
import { useMotionTransition } from "@/renderer/shared/ui/motion";
import { Button } from "@/renderer/shared/ui/shadcn/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/renderer/shared/ui/shadcn/tooltip";

/** Sliding distance for the artwork, title and artist. One value so they travel together. */
const SLIDE_PX = 16;

/** Next enters from the right and pushes the old track out to the left; previous mirrors it. */
const slide: Variants = {
  enter: (direction: 1 | -1) => ({ x: direction * SLIDE_PX, opacity: 0 }),
  center: { x: 0, opacity: 1 },
  exit: (direction: 1 | -1) => ({ x: -direction * SLIDE_PX, opacity: 0 }),
};

function useSlide() {
  const direction = usePlaybackNavigation() === "previous" ? -1 : 1;
  const transition = useMotionTransition("mediumMove");
  return { direction, transition } as const;
}

/** The artwork sleeve and, beside it, the title and artist (or the last command error). */
export function DockIdentity({ item, trackKey }: { item: PlaybackItem | null; trackKey: string }) {
  const { commandError } = usePlaybackTransport();
  const { isOpen: nowPlayingOpen, toggle: toggleNowPlaying } = useNowPlaying();
  const { direction, transition } = useSlide();
  const [errorTooltipOpen, setErrorTooltipOpen] = useState(false);
  const title = item?.title ?? "Nothing playing";

  return (
    <div className="col-start-1 flex min-w-0 items-center gap-3" data-region="playback-identity">
      <Sleeve item={item} trackKey={trackKey} />
      {nowPlayingOpen ? null : (
        <div className="relative flex min-w-0 flex-col justify-center gap-0.5">
          {/* Title and artist are one keyed block, so they leave and arrive as one piece. */}
          <AnimatePresence mode="popLayout" initial={false} custom={direction}>
            <m.div
              key={trackKey}
              custom={direction}
              variants={slide}
              initial="enter"
              animate="center"
              exit="exit"
              transition={transition}
              className="flex min-w-0 flex-col justify-center gap-0.5"
            >
              <button
                type="button"
                disabled={item === null}
                onClick={toggleNowPlaying}
                title={title}
                className="block max-w-full cursor-pointer truncate rounded-sm text-left text-sm font-medium text-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default"
              >
                {title}
              </button>
              {commandError ? (
                <Tooltip open={errorTooltipOpen} onOpenChange={setErrorTooltipOpen}>
                  <TooltipTrigger
                    render={
                      <span
                        className="block truncate text-sm text-destructive"
                        role="alert"
                        tabIndex={0}
                      />
                    }
                    onFocus={() => setErrorTooltipOpen(true)}
                    onBlur={() => setErrorTooltipOpen(false)}
                  >
                    {commandError}
                  </TooltipTrigger>
                  <TooltipContent>{commandError}</TooltipContent>
                </Tooltip>
              ) : item?.artist ? (
                <span className="block truncate text-sm text-muted-foreground" title={item.artist}>
                  {item.artist}
                </span>
              ) : null}
            </m.div>
          </AnimatePresence>
        </div>
      )}
    </div>
  );
}

function Sleeve({ item, trackKey }: { item: PlaybackItem | null; trackKey: string }) {
  const navigate = useNavigate();
  const { isOpen: nowPlayingOpen, toggle } = useNowPlaying();
  const { direction, transition } = useSlide();
  const hasTrack = item !== null;
  const albumKey = item?.albumKey ?? null;
  const artistName =
    albumKey?.albumArtist || item?.albumArtist?.trim() || item?.artist?.trim() || "";

  // Now Playing has its own big Sleeve (the shared-element target). While it is open this slot
  // holds the close affordance instead, so the dock's layout does not shift.
  if (nowPlayingOpen) {
    return (
      <Button
        type="button"
        variant="ghost"
        aria-label="Close Now Playing"
        onClick={toggle}
        data-slot="sleeve-close"
        className="size-16 shrink-0"
      >
        <ChevronDown aria-hidden="true" className="size-6" />
      </Button>
    );
  }

  return (
    <ContextMenu>
      <ContextMenuTrigger
        render={
          <button
            type="button"
            aria-label="Open Now Playing"
            disabled={!hasTrack}
            onClick={toggle}
            data-slot="sleeve"
            className={cn(
              // Inset, not edge-filling: a rounded tile that sits inside the identity column
              // like any other artwork placed in the workspace, rather than the dock's own
              // square edge treatment.
              "block aspect-square size-16 shrink-0 cursor-pointer overflow-hidden rounded-lg outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default",
            )}
          />
        }
      >
        <m.div
          layoutId={NOW_PLAYING_SLEEVE_ID}
          className="relative size-full overflow-hidden"
          style={{ borderRadius: SLEEVE_RADIUS_PX }}
        >
          <AnimatePresence mode="popLayout" initial={false} custom={direction}>
            <m.div
              key={trackKey}
              custom={direction}
              variants={slide}
              initial="enter"
              animate="center"
              exit="exit"
              transition={transition}
              className="size-full"
            >
              <Artwork
                artwork={item?.artwork ?? null}
                alt={item === null ? "" : `${item.title} artwork`}
                loading="eager"
                className="size-full rounded-lg"
              />
            </m.div>
          </AnimatePresence>
        </m.div>
      </ContextMenuTrigger>
      {hasTrack ? (
        <MenuContent side="right" align="start" className="min-w-40">
          {albumKey !== null ? (
            <MenuItem
              onClick={() =>
                void navigate({
                  to: "/library/albums/$albumArtist/$albumTitle",
                  params: {
                    albumArtist: toNameSegment(albumKey.albumArtist),
                    albumTitle: toNameSegment(albumKey.title),
                  },
                })
              }
            >
              Go to album
            </MenuItem>
          ) : null}
          {artistName !== "" ? (
            <MenuItem
              onClick={() =>
                void navigate({
                  to: "/library/album-artists/$artistName",
                  params: { artistName: toNameSegment(artistName) },
                })
              }
            >
              Go to artist
            </MenuItem>
          ) : null}
        </MenuContent>
      ) : null}
    </ContextMenu>
  );
}
