// src/lib/components/settings/playback-section.svelte
<script lang="ts">
  import { getPlayback } from "$lib/playback/context";
  import { createAudioOutputDevices } from "$lib/playback/output-devices.svelte";
  import { createPlaybackSignalPath } from "$lib/components/signal-path/signal-path.svelte";
  import { getSettings } from "$lib/settings/context";
  import type { SettingsUpdate } from "$lib/settings/settings.svelte";
  import FlapText from "$lib/ui/rolling-number/flap-text.svelte";
  import SectionTitle from "$lib/ui/section-title.svelte";
  import * as Select from "$lib/ui/shadcn/select/index.js";
  import SettingsSwitchField from "./settings-switch-field.svelte";

  const DEFAULT_DEVICE = "default";

  const playback = getPlayback();
  const settings = getSettings();
  const signalPath = createPlaybackSignalPath();

  let deviceMenuOpen = $state(false);
  const devices = createAudioOutputDevices(() => deviceMenuOpen);

  const path = $derived(signalPath.current);
  const selection = $derived(playback.outputSelection);
  const selected = $derived(selection.kind === "device" ? selection.deviceId : DEFAULT_DEVICE);
  const outputLabel = $derived(
    path?.output ?? (selection.kind === "device" ? "Output" : "System default"),
  );
  const rows = $derived([
    { label: "Source", value: path?.source ?? "—" },
    { label: "Processing", value: path?.processing ?? "None" },
  ]);

  function chooseDevice(value: string) {
    void playback.setOutputSelection(
      value === DEFAULT_DEVICE ? { kind: "systemDefault" } : { kind: "device", deviceId: value },
    );
  }

  // The store rolls a failed change back and records the error, which is shown below.
  function update(patch: SettingsUpdate) {
    void settings.update(patch);
  }
</script>

<section aria-labelledby="playback-heading" class="mt-8">
  <SectionTitle id="playback-heading">Playback</SectionTitle>
  <p class="mt-1 text-sm leading-5 text-muted-foreground">
    The current signal path and how artwork lights the app.
  </p>

  <!-- A technical ledger: each signal-path stage on the Gutter, next to its own setting. -->
  <dl class="mt-5 divide-y divide-border border-y border-border text-sm">
    {#each rows as row (row.label)}
      <div class="flex items-center gap-6 py-3">
        <dt class="w-16 shrink-0 text-muted-foreground">{row.label}</dt>
        <dd class="min-w-0 truncate tabular-nums text-foreground">
          <FlapText value={row.value} />
        </dd>
      </div>
    {/each}
    <div class="flex items-center gap-6 py-3">
      <dt class="w-16 shrink-0 text-muted-foreground">Output</dt>
      <dd class="min-w-0">
        <Select.Root
          type="single"
          bind:open={deviceMenuOpen}
          value={selected}
          onValueChange={chooseDevice}
        >
          <Select.Trigger
            disabled={playback.connection !== "ready"}
            aria-label={`Output device: ${outputLabel}`}
            class="h-auto min-w-0 cursor-pointer gap-1 rounded-sm border-0 bg-transparent p-0 text-foreground outline-none hover:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default disabled:opacity-50 dark:bg-transparent dark:hover:bg-transparent"
          >
            <span class="truncate tabular-nums">{outputLabel}</span>
          </Select.Trigger>
          <Select.Content align="start">
            <Select.Item value={DEFAULT_DEVICE} label="System default" />
            {#each devices.data ?? [] as device (device.id)}
              <Select.Item value={device.id} label={device.name} />
            {/each}
          </Select.Content>
        </Select.Root>
      </dd>
    </div>
  </dl>

  <SettingsSwitchField
    id="artwork-backdrop"
    label="Artwork backdrop"
    class="mt-5 border-y"
    checked={settings.artworkBackdrop}
    onChange={(checked) => update({ artworkBackdrop: checked })}
  >
    Light the playback dock and Now Playing with the current track's artwork.
  </SettingsSwitchField>

  <SettingsSwitchField
    id="calm-motion"
    label="Calm motion"
    checked={settings.calmMotion}
    onChange={(checked) => update({ calmMotion: checked })}
  >
    Only what marks the current position moves on its own: the Light stops breathing and lyric
    characters stop lifting.
  </SettingsSwitchField>

  {#if settings.error}
    <p class="mt-3 text-sm text-destructive" role="alert">{settings.error}</p>
  {/if}
</section>

// src-react/pages/settings/ui/playback-section.tsx
import { usePlaybackSignalPath } from "@/features/playback-signal-path";
import { useState } from "react";
import { ChevronDown } from "lucide-react";
import {
  usePlaybackActions,
  usePlaybackOutput,
  usePlaybackTransport,
  useAudioOutputDevices,
} from "@/entities/playback";
import { useArtworkBackdrop, useCalmMotion } from "@/entities/settings";
import { SectionTitle } from "@/shared/ui/headings";
import { Menu, MenuContent, MenuRadioGroup, MenuRadioItem, MenuTrigger } from "@/shared/ui/menu";
import { Field, FieldLabel } from "@/shared/ui/shadcn/field";
import { FlapText } from "@/shared/ui/rolling-number";
import { Switch } from "@/shared/ui/shadcn/switch";

const DEFAULT_DEVICE = "default";

/** A technical ledger: each signal-path stage on the Gutter, next to its own setting. */
export function PlaybackSection() {
  const { connection } = usePlaybackTransport();
  const { outputSelection: selection } = usePlaybackOutput();
  const playback = usePlaybackActions();
  const path = usePlaybackSignalPath();
  const artworkBackdrop = useArtworkBackdrop();
  const calmMotion = useCalmMotion();
  const [deviceMenuOpen, setDeviceMenuOpen] = useState(false);
  const devices = useAudioOutputDevices(deviceMenuOpen);
  const selected = selection.kind === "device" ? selection.deviceId : DEFAULT_DEVICE;
  const outputLabel = path?.output ?? (selection.kind === "device" ? "Output" : "System default");

  const rows: { label: string; value: string }[] = [
    { label: "Source", value: path?.source ?? "—" },
    { label: "Processing", value: path?.processing ?? "None" },
  ];

  return (
    <section aria-labelledby="playback-heading" className="mt-8">
      <SectionTitle id="playback-heading">Playback</SectionTitle>
      <p className="mt-1 text-sm leading-5 text-muted-foreground">
        The current signal path and how artwork lights the app.
      </p>

      <dl className="mt-5 divide-y divide-border border-y border-border text-sm">
        {rows.map((row) => (
          <div key={row.label} className="flex items-center gap-6 py-3">
            <dt className="w-16 shrink-0 text-muted-foreground">{row.label}</dt>
            <dd className="min-w-0 truncate tabular-nums text-foreground">
              <FlapText value={row.value} />
            </dd>
          </div>
        ))}
        <div className="flex items-center gap-6 py-3">
          <dt className="w-16 shrink-0 text-muted-foreground">Output</dt>
          <dd className="min-w-0">
            <Menu open={deviceMenuOpen} onOpenChange={setDeviceMenuOpen}>
              <MenuTrigger
                disabled={connection !== "ready"}
                aria-label={`Output device: ${outputLabel}`}
                className="flex min-w-0 cursor-pointer items-center gap-1 rounded-sm text-foreground outline-none hover:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default disabled:opacity-50"
              >
                <span className="truncate tabular-nums">{outputLabel}</span>
                <ChevronDown aria-hidden="true" className="size-3.5 shrink-0" />
              </MenuTrigger>
              <MenuContent>
                <MenuRadioGroup
                  value={selected}
                  onValueChange={(value) =>
                    void playback.setOutputSelection(
                      value === DEFAULT_DEVICE
                        ? { kind: "systemDefault" }
                        : { kind: "device", deviceId: String(value) },
                    )
                  }
                >
                  <MenuRadioItem value={DEFAULT_DEVICE}>System default</MenuRadioItem>
                  {(devices.data ?? []).map((device) => (
                    <MenuRadioItem key={device.id} value={device.id}>
                      {device.name}
                    </MenuRadioItem>
                  ))}
                </MenuRadioGroup>
              </MenuContent>
            </Menu>
          </dd>
        </div>
      </dl>

      <Field
        orientation="horizontal"
        className="mt-5 items-center justify-between gap-6 border-y border-border py-3 text-sm"
      >
        <FieldLabel htmlFor="artwork-backdrop" className="flex-col items-start gap-0.5">
          <span className="font-normal text-foreground">Artwork backdrop</span>
          <span className="max-w-prose text-sm leading-5 font-normal text-muted-foreground">
            Light the playback dock and Now Playing with the current track's artwork.
          </span>
        </FieldLabel>
        <Switch
          id="artwork-backdrop"
          checked={artworkBackdrop.enabled}
          onCheckedChange={(checked) => artworkBackdrop.setEnabled(checked)}
          className="shrink-0"
        />
      </Field>

      <Field
        orientation="horizontal"
        className="items-center justify-between gap-6 border-b border-border py-3 text-sm"
      >
        <FieldLabel htmlFor="calm-motion" className="flex-col items-start gap-0.5">
          <span className="font-normal text-foreground">Calm motion</span>
          <span className="max-w-prose text-sm leading-5 font-normal text-muted-foreground">
            Only what marks the current position moves on its own: the Light stops breathing and
            lyric characters stop lifting.
          </span>
        </FieldLabel>
        <Switch
          id="calm-motion"
          checked={calmMotion.enabled}
          onCheckedChange={(checked) => calmMotion.setEnabled(checked)}
          className="shrink-0"
        />
      </Field>
    </section>
  );
}
