// src/lib/ui/rolling-number/flap-text.svelte
<script lang="ts">
  import { prefersReducedMotion } from "svelte/motion";
  import { fade, type TransitionConfig } from "svelte/transition";
  import { motionFor } from "$lib/ui/motion/svelte-motion";

  /**
   * Text that flips over like a split-flap card when its value changes; an unchanged value does
   * not move, so a steady signal path stays still. Under reduced motion it crossfades.
   */
  let { value, class: className }: { value: string; class?: string } = $props();

  const reduced = $derived(prefersReducedMotion.current);

  /** Turns in from `from` degrees (and out to `-from`) while fading. */
  function flip(node: Element, { from }: { from: number }): TransitionConfig {
    if (reduced) return fade(node, motionFor("feedback"));
    const { duration, easing } = motionFor("move");
    return {
      duration,
      easing,
      css: (t, u) => `transform: rotateX(${from * u}deg); opacity: ${Math.min(1, t)}`,
    };
  }
</script>

<span class={className} style:perspective="400px">
  <span class="sr-only">{value}</span>
  <span aria-hidden="true" class="inline-grid">
    {#key value}
      <span
        data-glyph={value}
        class="inline-block whitespace-pre [grid-area:1/1] before:content-[attr(data-glyph)]"
        in:flip={{ from: -90 }}
        out:flip={{ from: 90 }}
        style:transform-origin="50% 50%"
      ></span>
    {/key}
  </span>
</span>

// src/renderer/shared/ui/rolling-number/flap-text.tsx
import { AnimatePresence, m, useReducedMotion } from "motion/react";
import { motionTokens } from "../motion/tokens";
import { useMotionTransition } from "../motion/use-motion-transition";

/**
 * Text that flips over like a split-flap card when its value changes; an unchanged value does
 * not move, so a steady signal path stays still. Under reduced motion it crossfades.
 */
export function FlapText({ value, className }: { value: string; className?: string }) {
  const reduced = useReducedMotion() === true;
  const transition = useMotionTransition("smallMove");
  return (
    <span className={className} style={{ perspective: 400 }}>
      <span className="sr-only">{value}</span>
      <span aria-hidden="true" className="inline-flex">
        <AnimatePresence initial={false} mode="popLayout">
          <m.span
            key={value}
            data-glyph={value}
            className="inline-block whitespace-pre before:content-[attr(data-glyph)]"
            initial={reduced ? { opacity: 0 } : { rotateX: -90, opacity: 0 }}
            animate={reduced ? { opacity: 1 } : { rotateX: 0, opacity: 1 }}
            exit={reduced ? { opacity: 0 } : { rotateX: 90, opacity: 0 }}
            transition={reduced ? motionTokens.feedback : transition}
            style={{ transformOrigin: "50% 50%" }}
          ></m.span>
        </AnimatePresence>
      </span>
    </span>
  );
}
