// src/routes/navigation.svelte
<script lang="ts">
  import Album from "@lucide/svelte/icons/album";
  import LibraryBig from "@lucide/svelte/icons/library-big";
  import ListMusic from "@lucide/svelte/icons/list-music";
  import Settings2 from "@lucide/svelte/icons/settings-2";
  import type { Component } from "svelte";
  import { resolve } from "$app/paths";
  import { page } from "$app/state";
  import { cn } from "$lib/utils/cn.js";
  import { buttonVariants } from "$lib/ui/shadcn/button/index.js";

  type NavigationItem = {
    label: string;
    to: "/library/albums" | "/library/album-artists" | "/library/tracks" | "/settings";
    icon: Component;
  };

  let { onNavigate }: { onNavigate?: () => void } = $props();

  const libraryItems: readonly NavigationItem[] = [
    { label: "Albums", to: "/library/albums", icon: LibraryBig },
    { label: "Album Artists", to: "/library/album-artists", icon: Album },
    { label: "Tracks", to: "/library/tracks", icon: ListMusic },
  ];
  const settingsItem: NavigationItem = { label: "Settings", to: "/settings", icon: Settings2 };

  function isActive(to: NavigationItem["to"]) {
    const pathname = page.url.pathname;
    return to === "/settings" ? pathname === to : pathname === to || pathname.startsWith(`${to}/`);
  }
</script>

{#snippet link(item: NavigationItem)}
  {@const active = isActive(item.to)}
  <a
    href={resolve(item.to)}
    aria-current={active ? "page" : undefined}
    onclick={onNavigate}
    class={cn(
      buttonVariants({ variant: "ghost", size: "lg" }),
      "relative h-10 w-full justify-start gap-2 px-2 text-muted-foreground hover:bg-sidebar-accent",
      active && "text-foreground",
    )}
  >
    {#if active}
      <span aria-hidden="true" class="absolute inset-0 rounded-md bg-muted"></span>
    {/if}
    <item.icon aria-hidden="true" class="relative" />
    <span class="relative truncate">{item.label}</span>
  </a>
{/snippet}

<nav
  aria-label="Application"
  class="flex min-h-0 flex-1 flex-col px-2 py-5 md:border-r md:border-sidebar-border"
>
  <div class="min-h-0 flex-1">
    <p class="mb-2 px-2 text-sm text-muted-foreground">Library</p>
    <div class="space-y-1">
      {#each libraryItems as item (item.to)}
        {@render link(item)}
      {/each}
    </div>
  </div>
  {@render link(settingsItem)}
</nav>

// src/app/renderer/ui/navigation.tsx
import { Album, LibraryBig, ListMusic, Settings2, type LucideIcon } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { cn } from "@/renderer/shared/lib/utils";
import { buttonVariants } from "@/renderer/shared/ui/shadcn/button";

type NavigationItem = {
  label: string;
  to: "/library/albums" | "/library/album-artists" | "/library/tracks" | "/settings";
  icon: LucideIcon;
};

const libraryItems: readonly NavigationItem[] = [
  { label: "Albums", to: "/library/albums", icon: LibraryBig },
  { label: "Album Artists", to: "/library/album-artists", icon: Album },
  { label: "Tracks", to: "/library/tracks", icon: ListMusic },
];

const settingsItem: NavigationItem = {
  label: "Settings",
  to: "/settings",
  icon: Settings2,
};

export function Navigation({
  pathname,
  onNavigate,
}: {
  pathname: string;
  onNavigate?: () => void;
}) {
  return (
    <nav
      aria-label="Application"
      className="flex min-h-0 flex-1 flex-col px-2 py-5 md:border-r md:border-sidebar-border"
    >
      <div className="min-h-0 flex-1">
        <p className="mb-2 px-2 text-sm text-muted-foreground">Library</p>
        <div className="space-y-1">
          {libraryItems.map((item) => (
            <NavigationLink
              item={item}
              key={item.to}
              active={isNavigationActive(pathname, item.to)}
              onNavigate={onNavigate}
            />
          ))}
        </div>
      </div>
      <NavigationLink
        item={settingsItem}
        active={isNavigationActive(pathname, settingsItem.to)}
        onNavigate={onNavigate}
      />
    </nav>
  );
}

function NavigationLink({
  item,
  active,
  onNavigate,
}: {
  item: NavigationItem;
  active: boolean;
  onNavigate?: () => void;
}) {
  const Icon = item.icon;

  return (
    <Link
      to={item.to}
      activeProps={{ "aria-current": "page" }}
      onClick={onNavigate}
      className={cn(
        buttonVariants({ variant: "ghost", size: "lg" }),
        "h-10 w-full justify-start gap-2 px-2 text-muted-foreground hover:bg-sidebar-accent",
        active && "bg-muted text-foreground hover:bg-muted",
      )}
    >
      <Icon aria-hidden="true" />
      <span className="truncate">{item.label}</span>
    </Link>
  );
}

function isNavigationActive(pathname: string, to: NavigationItem["to"]) {
  return to === "/settings" ? pathname === to : pathname === to || pathname.startsWith(`${to}/`);
}
