// src/routes/title-bar.svelte
<script lang="ts">
  import Menu from "@lucide/svelte/icons/menu";
  import X from "@lucide/svelte/icons/x";
  import { cn } from "$lib/utils/cn.js";
  import { buttonVariants } from "$lib/ui/shadcn/button/index.js";
  import {
    Sheet,
    SheetClose,
    SheetContent,
    SheetTitle,
    SheetTrigger,
  } from "$lib/ui/shadcn/sheet/index.js";
  import Navigation from "./navigation.svelte";
  import WindowControls from "./window-controls.svelte";

  let mobileNavigationOpen = $state(false);
</script>

<header
  class="col-span-full row-start-1 grid min-w-0 grid-cols-[minmax(0,1fr)_auto] border-b border-border bg-background md:grid-cols-[16rem_minmax(0,1fr)_auto]"
  data-slot="app-titlebar"
>
  <div class="flex min-w-0 items-center gap-2 border-sidebar-border px-2 md:border-r md:px-4">
    <Sheet bind:open={mobileNavigationOpen}>
      <SheetTrigger
        type="button"
        class={cn(buttonVariants({ variant: "ghost", size: "icon-lg" }), "md:hidden")}
        aria-label="Open navigation"
      >
        <Menu aria-hidden="true" class="size-4" />
      </SheetTrigger>
      <SheetContent
        side="left"
        showCloseButton={false}
        class="w-64 gap-0 border-sidebar-border bg-sidebar p-0 text-sidebar-foreground"
      >
        <div class="flex h-10 items-center justify-between border-b border-sidebar-border px-3">
          <SheetTitle class="text-sm font-normal">Nice Audio Player</SheetTitle>
          <SheetClose
            type="button"
            class={buttonVariants({ variant: "ghost", size: "icon-lg" })}
            aria-label="Close navigation"
          >
            <X aria-hidden="true" class="size-4" />
          </SheetClose>
        </div>
        <Navigation onNavigate={() => (mobileNavigationOpen = false)} />
      </SheetContent>
    </Sheet>
    <div aria-hidden="true" class="min-w-0 flex-1" data-tauri-drag-region></div>
  </div>
  <div aria-hidden="true" class="hidden min-w-0 md:block" data-tauri-drag-region></div>
  <WindowControls />
</header>

// src/app/renderer/ui/title-bar.tsx
import { useState } from "react";
import { Menu, X } from "lucide-react";
import { WindowControls } from "@/renderer/widgets/window-controls";
import { Button } from "@/renderer/shared/ui/shadcn/button";
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetTitle,
  SheetTrigger,
} from "@/renderer/shared/ui/shadcn/sheet";
import { Navigation } from "./navigation";

export function TitleBar({ pathname }: { pathname: string }) {
  const [mobileNavigationOpen, setMobileNavigationOpen] = useState(false);

  return (
    <header
      className="col-span-full row-start-1 grid min-w-0 grid-cols-[minmax(0,1fr)_auto] border-b border-border bg-background md:grid-cols-[16rem_minmax(0,1fr)_auto]"
      data-slot="app-titlebar"
    >
      <div className="flex min-w-0 items-center gap-2 border-sidebar-border px-2 md:border-r md:px-4">
        <Sheet open={mobileNavigationOpen} onOpenChange={setMobileNavigationOpen}>
          <SheetTrigger
            render={
              <Button
                type="button"
                variant="ghost"
                size="icon-lg"
                className="md:hidden"
                aria-label="Open navigation"
              />
            }
          >
            <Menu aria-hidden="true" className="size-4" />
          </SheetTrigger>
          <SheetContent
            side="left"
            showCloseButton={false}
            className="w-64 gap-0 border-sidebar-border bg-sidebar p-0 text-sidebar-foreground"
          >
            <div className="flex h-10 items-center justify-between border-b border-sidebar-border px-3">
              <SheetTitle className="text-sm font-medium">Nice Audio Player</SheetTitle>
              <SheetClose
                render={
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon-lg"
                    aria-label="Close navigation"
                  />
                }
              >
                <X aria-hidden="true" className="size-4" />
              </SheetClose>
            </div>
            <Navigation pathname={pathname} onNavigate={() => setMobileNavigationOpen(false)} />
          </SheetContent>
        </Sheet>
        <div aria-hidden="true" className="min-w-0 flex-1" data-tauri-drag-region />
      </div>
      <div aria-hidden="true" className="hidden min-w-0 md:block" data-tauri-drag-region />
      <WindowControls />
    </header>
  );
}
