// src/lib/ui/artwork.svelte
<script lang="ts">
  import { artworkUrl, type ArtworkRef } from "$lib/native";
  import { cn } from "$lib/utils/cn.js";

  let {
    artwork,
    alt = "",
    loading = "lazy",
    class: className,
  }: {
    artwork: ArtworkRef | null | undefined;
    alt?: string;
    loading?: "eager" | "lazy";
    class?: string;
  } = $props();

  const url = $derived(artworkUrl(artwork));
  let failedUrl = $state<string | null>(null);
  const showImage = $derived(url !== null && failedUrl !== url);
</script>

<!-- The Sleeve: a square of artwork, or a quiet block when there is none. -->
<span
  data-slot="artwork"
  class={cn("block aspect-square overflow-hidden rounded-lg bg-muted", className)}
>
  {#if showImage}
    <img
      src={url}
      {alt}
      {loading}
      class="size-full object-cover"
      onerror={() => (failedUrl = url)}
    />
  {:else}
    <span aria-hidden="true" class="block size-full bg-muted"></span>
  {/if}
</span>

// src/renderer/shared/ui/artwork.tsx
import { useState } from "react";
import type { ArtworkRef } from "@/shared/ipc";
import { artworkUrl } from "@/renderer/shared/lib/artwork-url";
import { cn } from "@/renderer/shared/lib/utils";

type ArtworkProps = {
  artwork: ArtworkRef | null | undefined;
  alt?: string;
  loading?: "eager" | "lazy";
  className?: string;
};

function Artwork({ artwork, alt = "", loading = "lazy", className }: ArtworkProps) {
  const url = artworkUrl(artwork);
  const [failedUrl, setFailedUrl] = useState<string | null>(null);
  const showImage = url !== null && failedUrl !== url;

  return (
    <span
      data-slot="artwork"
      className={cn("block aspect-square overflow-hidden rounded-lg bg-muted", className)}
    >
      {showImage ? (
        <img
          src={url}
          alt={alt}
          loading={loading}
          className="size-full object-cover"
          onError={() => setFailedUrl(url)}
        />
      ) : (
        <span aria-hidden="true" className="block size-full bg-muted" />
      )}
    </span>
  );
}

export { Artwork };
