// src/lib/ui/kinetic-text.svelte
<script lang="ts">
  import { animate } from "motion";
  import { prefersReducedMotion } from "svelte/motion";
  import type { Attachment } from "svelte/attachments";
  import { toMotionOptions } from "$lib/ui/motion/motion-options";
  import { motionTokens } from "$lib/ui/motion/tokens";
  import { REVEAL_END_PERCENT, wipeMask } from "$lib/ui/wipe-mask";
  import { cn } from "$lib/utils/cn.js";

  /**
   * Text that wipes in from left to right while it slides 8px from the side the track came from
   * (`direction` 1 = from the right). Shown only for track changes, never on first display; key
   * it by what it shows so a new value plays again.
   *
   * Only the real text is drawn, so it stays selectable and readable by assistive technology, and
   * wrapping, kerning and line breaks are the same from the first frame to the last: the
   * animation is a mask and a transform, and never changes the layout. Under reduced motion it
   * is a plain crossfade.
   */
  let {
    text,
    direction,
    class: className,
  }: {
    text: string;
    direction: 1 | -1;
    class?: string;
  } = $props();

  const options = toMotionOptions(motionTokens.mediumMove);
  const reduced = prefersReducedMotion.current;

  // Plays once per mount. The wipe ends past the text, so once it is done the mask clips nothing
  // (and is removed).
  const play: Attachment<HTMLElement> = (node) => {
    if (reduced) {
      const fade = animate(node, { opacity: [0, 1] }, options);
      return () => fade.stop();
    }
    const slide = animate(node, { x: [8 * direction, 0] }, options);
    const wipe = animate(0, REVEAL_END_PERCENT, {
      ...options,
      onUpdate: (percent) => {
        const mask = wipeMask(percent);
        node.style.maskImage = mask;
        node.style.webkitMaskImage = mask;
      },
      onComplete: () => {
        node.style.maskImage = "";
        node.style.webkitMaskImage = "";
      },
    });
    return () => {
      slide.stop();
      wipe.stop();
    };
  };
</script>

<!-- Hidden at first so the frame before the animation starts does not flash the full text. -->
<span
  {@attach play}
  class={cn("block", className)}
  style:opacity={reduced ? 0 : undefined}
  style:mask-image={reduced ? undefined : wipeMask(0)}
  style:-webkit-mask-image={reduced ? undefined : wipeMask(0)}>{text}</span
>

// src/renderer/shared/ui/kinetic-text.tsx
import { animate, m, useMotionValue, useReducedMotion, useTransform } from "motion/react";
import { useEffect } from "react";
import { cn } from "@/renderer/shared/lib/utils";
import { useMotionTransition } from "./motion";

/** How far the soft edge of the wipe reaches behind its front, in percent of the text width. */
const EDGE_PERCENT = 20;
/** The wipe front travels this far so the soft edge clears the end of the text. */
const REVEAL_END_PERCENT = 100 + EDGE_PERCENT;

/**
 * Text that wipes in from left to right while it slides 8px from the side the track came from
 * (`direction` 1 = from the right). Shown only for track changes, never on first display; key it
 * by what it shows so a new value plays again.
 *
 * Only the real text is drawn, so wrapping, kerning and line breaks are the same from the first
 * frame to the last: the animation is a mask and a transform, and never changes the layout.
 * Under reduced motion it is a plain crossfade.
 */
export function KineticText({
  text,
  direction,
  className,
}: {
  text: string;
  direction: 1 | -1;
  className?: string;
}) {
  const transition = useMotionTransition("mediumMove");
  const reducedMotion = useReducedMotion() === true;
  const reveal = useMotionValue(0);
  const maskImage = useTransform(
    reveal,
    (value) =>
      `linear-gradient(to right, black calc(${value}% - ${EDGE_PERCENT}%), transparent ${value}%)`,
  );

  useEffect(() => {
    if (reducedMotion) return;
    const controls = animate(reveal, REVEAL_END_PERCENT, transition);
    return () => controls.stop();
    // The transition object is stable per token; the wipe plays once per mount.
    // oxlint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <m.span
      className={cn("block", className)}
      initial={reducedMotion ? { opacity: 0 } : { x: 8 * direction }}
      animate={reducedMotion ? { opacity: 1 } : { x: 0 }}
      transition={transition}
      // The wipe ends past the text, so once it is done the mask clips nothing.
      style={reducedMotion ? undefined : { maskImage, WebkitMaskImage: maskImage }}
    >
      {text}
    </m.span>
  );
}
