// src/routes/window-controls.svelte
<script lang="ts">
  import Copy from "@lucide/svelte/icons/copy";
  import Minus from "@lucide/svelte/icons/minus";
  import Square from "@lucide/svelte/icons/square";
  import X from "@lucide/svelte/icons/x";
  import { nativeWindow } from "$lib/native";
  import { Button } from "$lib/ui/shadcn/button/index.js";

  const appWindow = nativeWindow;
  let maximized = $state(false);

  $effect(() => {
    if (appWindow === null) return;
    return appWindow.onMaximizedChange((value) => {
      maximized = value;
    });
  });
</script>

{#if appWindow !== null}
  <div class="flex h-10 shrink-0 items-stretch" aria-label="Window controls" role="group">
    <Button
      type="button"
      variant="ghost"
      class="size-10 rounded-none"
      aria-label="Minimize window"
      onclick={() => void appWindow.minimize()}
    >
      <Minus aria-hidden="true" class="size-4" />
    </Button>
    <Button
      type="button"
      variant="ghost"
      class="size-10 rounded-none"
      aria-label={maximized ? "Restore window" : "Maximize window"}
      onclick={() => void appWindow.toggleMaximize()}
    >
      {#if maximized}
        <Copy aria-hidden="true" class="size-3.5" />
      {:else}
        <Square aria-hidden="true" class="size-3.5" />
      {/if}
    </Button>
    <Button
      type="button"
      variant="ghost"
      class="size-10 rounded-none hover:bg-destructive hover:text-destructive-foreground"
      aria-label="Close window"
      onclick={() => void appWindow.close()}
    >
      <X aria-hidden="true" class="size-4" />
    </Button>
  </div>
{/if}

// src/renderer/widgets/window-controls/window-controls.tsx
import { useEffect, useState } from "react";
import { Copy, Minus, Square, X } from "lucide-react";
import { isTauri } from "@tauri-apps/api/core";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { Button } from "@/renderer/shared/ui/shadcn/button";

function WindowControls() {
  const [maximized, setMaximized] = useState(false);
  const desktop = isTauri();

  useEffect(() => {
    if (!desktop) return;

    const appWindow = getCurrentWindow();
    let disposed = false;
    let unlisten: (() => void) | undefined;

    const syncMaximized = () =>
      void appWindow.isMaximized().then((value) => {
        if (!disposed) setMaximized(value);
      });

    syncMaximized();
    void appWindow.onResized(syncMaximized).then((stopListening) => {
      if (disposed) stopListening();
      else unlisten = stopListening;
    });

    return () => {
      disposed = true;
      unlisten?.();
    };
  }, [desktop]);

  if (!desktop) return null;

  return (
    <div className="flex h-10 shrink-0 items-stretch" aria-label="Window controls" role="group">
      <Button
        type="button"
        variant="ghost"
        className="size-10 rounded-none"
        aria-label="Minimize window"
        onClick={() => void getCurrentWindow().minimize()}
      >
        <Minus aria-hidden="true" className="size-4" />
      </Button>
      <Button
        type="button"
        variant="ghost"
        className="size-10 rounded-none"
        aria-label={maximized ? "Restore window" : "Maximize window"}
        onClick={() => void getCurrentWindow().toggleMaximize()}
      >
        {maximized ? (
          <Copy aria-hidden="true" className="size-3.5" />
        ) : (
          <Square aria-hidden="true" className="size-3.5" />
        )}
      </Button>
      <Button
        type="button"
        variant="ghost"
        className="size-10 rounded-none hover:bg-destructive hover:text-destructive-foreground"
        aria-label="Close window"
        onClick={() => void getCurrentWindow().close()}
      >
        <X aria-hidden="true" className="size-4" />
      </Button>
    </div>
  );
}

export { WindowControls };
