// src/lib/components/now-playing/now-playing-light.svelte
<script lang="ts">
  import { getPlayback } from "$lib/playback/context";
  import { createLoudnessLevel } from "$lib/playback/loudness-level";
  import { createPlaybackWaveform } from "$lib/playback/waveform.svelte";
  import { getSettings } from "$lib/settings/context";
  import { getMotionBudget } from "$lib/shell/motion-budget.svelte";
  import ArtworkLight from "$lib/ui/artwork-light/artwork-light.svelte";

  /**
   * Now Playing's Light, which breathes with the track's loudness (never brighter than its
   * strength). It follows the playback clock directly, so nothing re-renders with time. The
   * breathing is off under calm or reduced motion, and then nothing here runs per frame.
   */
  const playback = getPlayback();
  const settings = getSettings();
  const budget = getMotionBudget();

  const item = $derived(playback.item);
  // The Light breathes by itself, so only the full budget allows it.
  const breathing = $derived(budget.current === "full");
  const playing = $derived(playback.status === "playing");
  const waveform = createPlaybackWaveform(() => playback.playbackId);

  const loudness = createLoudnessLevel({
    clock: playback.clock,
    rms: null,
    durationMs: null,
    playing: false,
    enabled: false,
  });
  $effect(() => {
    loudness.update({
      rms: waveform.current?.rms ?? null,
      durationMs: playback.durationMs,
      playing,
      enabled: breathing,
    });
  });
  $effect(() => () => loudness.destroy());
</script>

{#if settings.artworkBackdrop}
  <ArtworkLight
    artwork={item?.artwork ?? null}
    strength="max"
    enter={playback.lastNavigation === "previous" ? "wipe-previous" : "wipe-next"}
    level={breathing ? loudness.level : undefined}
  />
{/if}

// src/renderer/widgets/now-playing/ui/now-playing-light.tsx
import {
  usePlaybackItem,
  usePlaybackClock,
  usePlaybackDuration,
  usePlaybackNavigation,
  usePlaybackTransport,
  usePlaybackWaveform,
} from "@/renderer/entities/playback";
import { useLoudnessLevel } from "@/renderer/features/now-playing-transition";
import { ArtworkLight } from "@/renderer/shared/ui/artwork-light";
import { useMotionBudget } from "@/renderer/shared/ui/motion";

/**
 * Now Playing's Light, which breathes with the track's loudness (never brighter than its
 * strength). It follows the playback clock through motion values, so nothing re-renders with
 * time. The breathing is off under calm or reduced motion, and then nothing here runs per frame.
 */
export function NowPlayingLight() {
  const item = usePlaybackItem();
  const navigation = usePlaybackNavigation();
  const durationMs = usePlaybackDuration();
  const playing = usePlaybackTransport().status === "playing";
  // The Light breathes by itself, so only the full budget allows it.
  const reduced = useMotionBudget() !== "full";
  const rms = usePlaybackWaveform(item?.file.path ?? null)?.rms ?? null;
  const position = usePlaybackClock(!reduced);
  const level = useLoudnessLevel(rms, position, durationMs, playing, !reduced);

  return (
    <ArtworkLight
      artwork={item?.artwork ?? null}
      strength="max"
      enter={navigation === "previous" ? "wipe-previous" : "wipe-next"}
      level={reduced ? undefined : level}
    />
  );
}
