// src/lib/components/dock/playback-region.svelte
<script lang="ts">
  import { createNowPlayingTween } from "$lib/shell/now-playing-tween.svelte";
  import { DOCK_HEIGHT_NOW_PLAYING_PX, DOCK_HEIGHT_PX } from "./dock-metrics";
  import PlaybackDock from "./playback-dock.svelte";

  const height = createNowPlayingTween(DOCK_HEIGHT_PX, DOCK_HEIGHT_NOW_PLAYING_PX);
</script>

<!--
  The transport row is pinned EDGE_PX from this box's bottom edge (see PlaybackDock), which is
  what keeps it from moving on screen when Now Playing opens or closes: this row sits in a
  fixed-height grid track whose bottom edge is the window's own bottom edge, so changing this
  box's height only ever eats into the library area above it, never the dock's bottom. While Now
  Playing is open the box is exactly row + top gap + bottom gap (see dock-metrics.ts), which makes
  that leftover top gap equal the bottom gap.

  The height is animated as a real height, not a transform: scaling would squash the transport
  buttons and the artwork light inside it.
-->
<div class="flex min-h-0 min-w-0 flex-col">
  <div class="min-h-0 shrink-0" style:height="{height.current}px">
    <PlaybackDock />
  </div>
</div>

// src/renderer/widgets/playback-region/playback-region.tsx
import { m } from "motion/react";
import { useMotionTransition } from "@/renderer/shared/ui/motion";
import { PlaybackDock } from "./playback-dock";
import { PlaybackStatusBar } from "./playback-status-bar";
import { cn } from "@/renderer/shared/lib/utils";

export function PlaybackRegion({
  nowPlayingOpen,
  onToggleNowPlaying,
}: {
  nowPlayingOpen: boolean;
  onToggleNowPlaying: () => void;
}) {
  const nowPlayingTransition = useMotionTransition("largeMove");

  return (
    <div className="flex min-h-0 min-w-0 flex-col">
      {/*
       * The transport row is pinned `pb-3` from this box's bottom edge (see PlaybackDock), which
       * is what keeps it from moving on screen when Now Playing opens or closes: this row sits in
       * a fixed-height grid track whose bottom edge is the window's own bottom edge, so animating
       * this box's height only ever eats into the library area above it, never the dock's bottom.
       * Sizing the box to exactly row + top gap + bottom gap (64 + 12 + 12 = 88px) while Now
       * Playing is open makes that leftover top gap equal the `pb-3` bottom gap, instead of the
       * full slack of the taller collapsed-state box; `layout` animates the change between the
       * two instead of snapping.
       */}
      <m.div
        layout
        transition={nowPlayingTransition}
        className={cn("min-h-0 shrink-0", nowPlayingOpen ? "h-22" : "h-26")}
      >
        <PlaybackDock nowPlayingOpen={nowPlayingOpen} onToggleNowPlaying={onToggleNowPlaying} />
      </m.div>
      <PlaybackStatusBar />
    </div>
  );
}
