// src/renderer/pages/settings/ui/remove-library-root-dialog.tsx
import type { LibraryRoot } from "@/renderer/entities/library";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/renderer/shared/ui/shadcn/alert-dialog";

export function RemoveLibraryRootDialog({
  root,
  onOpenChange,
  onConfirm,
}: {
  root: LibraryRoot | null;
  onOpenChange: (open: boolean) => void;
  onConfirm: () => void;
}) {
  return (
    <AlertDialog open={root !== null} onOpenChange={onOpenChange}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Remove library folder?</AlertDialogTitle>
          <AlertDialogDescription className="break-words text-foreground">
            {root?.path}
          </AlertDialogDescription>
        </AlertDialogHeader>
        <p className="text-sm leading-5 text-muted-foreground">
          This removes indexed library records for this folder. It does not delete audio files.
        </p>
        <AlertDialogFooter>
          <AlertDialogCancel>Cancel</AlertDialogCancel>
          <AlertDialogAction variant="destructive" onClick={onConfirm}>
            Remove
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}

// src/routes/settings/remove-library-root-dialog.svelte
<script lang="ts">
  import type { LibraryRoot } from "$lib/native";
  import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
  } from "$lib/ui/shadcn/alert-dialog/index.js";

  let {
    root,
    onOpenChange,
    onConfirm,
  }: {
    root: LibraryRoot | null;
    onOpenChange: (open: boolean) => void;
    onConfirm: () => void;
  } = $props();
</script>

<AlertDialog open={root !== null} {onOpenChange}>
  <AlertDialogContent>
    <AlertDialogHeader>
      <AlertDialogTitle>Remove library folder?</AlertDialogTitle>
      <AlertDialogDescription class="break-words text-foreground">
        {root?.path}
      </AlertDialogDescription>
    </AlertDialogHeader>
    <p class="text-sm leading-5 text-muted-foreground">
      This removes indexed library records for this folder. It does not delete audio files.
    </p>
    <AlertDialogFooter>
      <AlertDialogCancel>Cancel</AlertDialogCancel>
      <AlertDialogAction variant="destructive" onclick={onConfirm}>Remove</AlertDialogAction>
    </AlertDialogFooter>
  </AlertDialogContent>
</AlertDialog>
