// src/lib/components/queue-panel/queue-panel.svelte
<script lang="ts">
  import type { Attachment } from "svelte/attachments";
  import { getPlayback } from "$lib/playback/context";
  import { queuePanel } from "$lib/shell/queue-panel.svelte";
  import { Sheet, SheetContent, SheetHeader, SheetTitle } from "$lib/ui/shadcn/sheet";
  import QueueFooter from "./queue-footer.svelte";
  import QueueRow from "./queue-row.svelte";
  import { createShuffleCascade } from "./shuffle-cascade.svelte";
  import UpcomingList from "./upcoming-list.svelte";

  const playback = getPlayback();

  const queue = $derived(playback.queue);
  const history = $derived(queue?.history ?? []);
  const cascade = createShuffleCascade(
    () => playback.shuffleEnabled,
    () => queuePanel.isOpen,
  );

  let scrollElement = $state<HTMLDivElement | null>(null);
  let content = $state<HTMLDivElement | null>(null);

  // Opening the panel shows the current track at the top, with what was played above it.
  const showAtTop: Attachment<HTMLElement> = (node) => {
    node.scrollIntoView({ block: "start" });
  };
</script>

<!-- Not modal: the library stays visible and usable beside the queue, so there is no backdrop and
     a click elsewhere does not close it (Escape and the queue button do). -->
<Sheet
  open={queuePanel.isOpen}
  onOpenChange={(open) => (open ? queuePanel.open() : queuePanel.close())}
>
  <SheetContent
    side="right"
    class="w-80 gap-0 p-0"
    overlay={false}
    showCloseButton={false}
    interactOutsideBehavior="ignore"
    trapFocus={false}
    preventScroll={false}
  >
    <div class="border-b border-border">
      <SheetHeader>
        <SheetTitle>Queue</SheetTitle>
      </SheetHeader>
    </div>
    <div bind:this={scrollElement} class="min-h-0 flex-1 overflow-y-auto py-2">
      <div bind:this={content}>
        {#each history as item (item.id)}
          <QueueRow {item} tone="past" onPlay={() => void playback.playQueueItem(item.id)} />
        {/each}
        {#if queue?.current}
          <div {@attach showAtTop}>
            <QueueRow item={queue.current} tone="current" />
          </div>
        {:else}
          <p class="px-4 py-6 text-sm text-muted-foreground">Nothing playing.</p>
        {/if}
        {#if queue && queue.upcomingCount > 0}
          <UpcomingList {scrollElement} {content} cascading={cascade.current} />
        {/if}
      </div>
    </div>
    <QueueFooter />
  </SheetContent>
</Sheet>

// src/renderer/widgets/queue-panel/ui/queue-panel.tsx
import { ChevronDown, ChevronUp, X } from "lucide-react";
import type { PlaybackQueueItem } from "@/shared/ipc";
import { usePlaybackActions, usePlaybackQueue } from "@/renderer/entities/playback";
import { formatDuration } from "@/renderer/shared/lib/format";
import { cn } from "@/renderer/shared/lib/utils";
import { Artwork } from "@/renderer/shared/ui/artwork";
import { Button } from "@/renderer/shared/ui/shadcn/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/renderer/shared/ui/shadcn/sheet";
import { useQueuePanel } from "../model/use-queue-panel";

/**
 * A 320px Acrylic panel from the right (DESIGN.md, Queue). Reordering moves an item one slot
 * at a time (`moveQueueItem`) rather than free drag: the backend queue only exposes earlier/
 * later moves, and that is enough for a personal-project queue of a few dozen tracks.
 */
export function QueuePanel() {
  const { isOpen, close } = useQueuePanel();
  const { queue } = usePlaybackQueue();
  const playback = usePlaybackActions();

  return (
    // Not modal: the library stays visible and usable beside the queue, so there is no backdrop
    // and a click elsewhere does not close it (Escape and the queue button do).
    <Sheet
      open={isOpen}
      modal={false}
      disablePointerDismissal
      onOpenChange={(open) => (open ? undefined : close())}
    >
      <SheetContent side="right" overlay={false} className="w-80 gap-0 p-0" aria-label="Queue">
        <SheetHeader className="border-b border-border pb-4">
          <SheetTitle>Queue</SheetTitle>
        </SheetHeader>
        <div className="min-h-0 flex-1 overflow-y-auto py-2">
          {queue?.current ? (
            <QueueRow item={queue.current} tone="current" />
          ) : (
            <p className="px-4 py-6 text-sm text-muted-foreground">Nothing playing.</p>
          )}
          {queue && queue.upcoming.length > 0 ? (
            <ul>
              {queue.upcoming.map((item, index) => (
                <li key={item.id}>
                  <QueueRow
                    item={item}
                    tone="upcoming"
                    onMoveEarlier={() => void playback.moveQueueItem(item.id, "earlier")}
                    onMoveLater={() => void playback.moveQueueItem(item.id, "later")}
                    canMoveEarlier={index > 0}
                    canMoveLater={index < queue.upcoming.length - 1}
                    onRemove={() => void playback.removeQueueItem(item.id)}
                  />
                </li>
              ))}
            </ul>
          ) : null}
        </div>
        {queue && queue.upcoming.length > 0 ? (
          <div className="border-t border-border p-3">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="w-full"
              onClick={() => void playback.clearQueue()}
            >
              Clear upcoming
            </Button>
          </div>
        ) : null}
      </SheetContent>
    </Sheet>
  );
}

function QueueRow({
  item,
  tone,
  onMoveEarlier,
  onMoveLater,
  canMoveEarlier,
  canMoveLater,
  onRemove,
}: {
  item: PlaybackQueueItem;
  tone: "current" | "upcoming";
  onMoveEarlier?: () => void;
  onMoveLater?: () => void;
  canMoveEarlier?: boolean;
  canMoveLater?: boolean;
  onRemove?: () => void;
}) {
  return (
    <div
      className="group/queue-row flex min-w-0 items-center gap-2 px-4 py-2"
      data-tone={tone}
      aria-current={tone === "current" ? "true" : undefined}
    >
      <Artwork artwork={item.artwork} className="size-10 shrink-0 rounded-md" />
      <div className="min-w-0 flex-1">
        <p
          className={cn(
            "truncate text-sm",
            tone === "current" ? "text-foreground" : "text-muted-foreground",
          )}
        >
          {item.title}
        </p>
        {item.artist ? (
          <p className="truncate text-xs text-muted-foreground">{item.artist}</p>
        ) : null}
      </div>
      <span className="shrink-0 text-xs tabular-nums text-muted-foreground">
        {formatDuration(item.durationMs ?? null)}
      </span>
      {tone === "upcoming" ? (
        <div className="flex shrink-0 items-center opacity-0 focus-within:opacity-100 group-hover/queue-row:opacity-100">
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            aria-label="Move earlier in queue"
            disabled={!canMoveEarlier}
            onClick={onMoveEarlier}
          >
            <ChevronUp aria-hidden="true" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            aria-label="Move later in queue"
            disabled={!canMoveLater}
            onClick={onMoveLater}
          >
            <ChevronDown aria-hidden="true" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            aria-label={`Remove ${item.title} from queue`}
            onClick={onRemove}
          >
            <X aria-hidden="true" />
          </Button>
        </div>
      ) : null}
    </div>
  );
}
