// src/routes/library/library-workspace.svelte
<script lang="ts" module>
  import type { LibraryViewState } from "$lib/library/catalog.svelte";
  import type { LibrarySortDirection } from "$lib/native";
  import type { SortOption } from "$lib/ui/sort-option";

  export type LibraryPresentationMeta = {
    title: string;
    singular: string;
    plural: string;
    searchLabel: string;
    searchPlaceholder: string;
  };

  export type LibraryScroll = {
    /** `null` until the scroll region has mounted. */
    viewport: HTMLElement | null;
    initialOffset: number;
    /** The list reports the index of its first visible item here (for the scroll index). */
    ontopindexchange: (index: number) => void;
  };

  /** What the workspace reads from `createLibraryCatalog`. */
  export type WorkspaceCatalog<Item> = {
    statusQuery: { error: unknown; refetch: () => unknown };
    statusMessage: string | null;
    viewState: LibraryViewState;
    updating: boolean;
    items: readonly Item[];
    totalCount: number | null;
    error: unknown;
    hasNextPage: boolean;
    isFetchingNextPage: boolean;
    fetchNextPage: () => unknown;
    refetch: () => unknown;
  };

  /** How long the scroll index stays after the last scroll. */
  const INDEX_HOLD_MS = 800;
</script>

<script lang="ts" generics="Item, Key extends string">
  import type { Snippet } from "svelte";
  import { untrack } from "svelte";
  import { resolve } from "$app/paths";
  import { libraryCommandErrorMessage } from "$lib/library/library-errors";
  import { recallScroll, rememberScroll } from "$lib/shell/scroll-memory";
  import EmptyStatus from "$lib/ui/empty-status.svelte";
  import ErrorAlert from "$lib/ui/error-alert.svelte";
  import LoadMoreSentinel from "$lib/ui/load-more-sentinel.svelte";
  import LoadingStatus from "$lib/ui/loading-status.svelte";
  import ScrollIndex from "$lib/ui/scroll-index.svelte";
  import WorkspaceScroll from "$lib/ui/workspace-scroll.svelte";
  import { formatCount } from "$lib/utils/format";
  import LibraryToolbar from "./library-toolbar.svelte";

  let {
    meta,
    scrollKey,
    filter,
    onfilterchange,
    stateKey,
    sort,
    catalog,
    indexFor,
    content,
  }: {
    meta: LibraryPresentationMeta;
    /** The path of the view, under which its scroll position is remembered. */
    scrollKey: string;
    filter: string;
    onfilterchange: (filter: string) => void;
    /** Changes when the filter or sort does, returning the list to the top. */
    stateKey: string;
    sort?: {
      key: Key;
      direction: LibrarySortDirection;
      options: readonly SortOption<Key>[];
      onkeychange: (key: Key) => void;
      ontoggledirection: () => void;
    };
    catalog: WorkspaceCatalog<Item>;
    /**
     * The index key of an item (a letter or a year) for the big label shown while scrolling.
     * The list must report its first visible item through `scroll.ontopindexchange`.
     */
    indexFor?: (item: Item) => string;
    content: Snippet<[readonly Item[], LibraryScroll]>;
  } = $props();

  let viewport = $state<HTMLElement | null>(null);
  // Read once: the list is built at this offset, then scrolling keeps the memory current.
  const initialOffset = untrack(() => recallScroll(scrollKey));
  let topIndex = $state(0);
  let scrolling = $state(false);

  $effect(() => {
    const element = viewport;
    if (element === null) return;
    let hold: ReturnType<typeof setTimeout> | undefined;
    const onScroll = () => {
      rememberScroll(scrollKey, element.scrollTop);
      scrolling = true;
      clearTimeout(hold);
      hold = setTimeout(() => (scrolling = false), INDEX_HOLD_MS);
    };
    element.addEventListener("scroll", onScroll, { passive: true });
    return () => {
      element.removeEventListener("scroll", onScroll);
      clearTimeout(hold);
    };
  });

  // Back to the top when the filter or sort changes, but not on first run.
  let previousKey: string | null = null;
  $effect(() => {
    const key = stateKey;
    const element = viewport;
    const previous = previousKey;
    previousKey = key;
    if (previous === null || previous === key || element === null) return;
    element.scrollTo({ top: 0 });
    rememberScroll(scrollKey, 0);
  });

  const item = $derived(catalog.items[topIndex]);
  const scrollIndexLabel = $derived(
    indexFor === undefined || item === undefined ? null : indexFor(item),
  );

  const scroll = $derived<LibraryScroll>({
    viewport,
    initialOffset,
    ontopindexchange: (index) => (topIndex = index),
  });
</script>

<div class="grid h-full min-h-0 min-w-0 grid-rows-[auto_minmax(0,1fr)] overflow-hidden">
  <LibraryToolbar
    title={meta.title}
    countLabel={formatCount(catalog.totalCount, meta.singular, meta.plural)}
    searchLabel={meta.searchLabel}
    searchPlaceholder={meta.searchPlaceholder}
    {filter}
    updating={catalog.updating}
    {onfilterchange}
    {sort}
  />

  <div class="@container relative min-h-0">
    <ScrollIndex label={scrollIndexLabel} visible={scrolling} />
    <WorkspaceScroll bind:viewportRef={viewport} contentClass="pt-6 pb-16">
      {#if catalog.viewState === "loading"}
        <LoadingStatus>Loading library…</LoadingStatus>
      {:else if catalog.viewState === "statusError"}
        <ErrorAlert
          message={libraryCommandErrorMessage(catalog.statusQuery.error)}
          onRetry={() => void catalog.statusQuery.refetch()}
        />
      {:else if catalog.viewState === "unavailable"}
        <ErrorAlert message={catalog.statusMessage ?? ""} />
      {:else if catalog.viewState === "catalogError"}
        <ErrorAlert
          message={libraryCommandErrorMessage(catalog.error)}
          onRetry={() => void catalog.refetch()}
        />
      {:else if catalog.viewState === "empty"}
        <EmptyStatus>
          {#if filter === ""}
            No {meta.plural} in your library.
            <a href={resolve("/settings")} class="text-foreground underline underline-offset-4">
              Add a music folder
            </a>
          {:else}
            No results for “{filter}”.
          {/if}
        </EmptyStatus>
      {:else}
        {@render content(catalog.items, scroll)}
        {#if catalog.hasNextPage}
          <LoadMoreSentinel
            {viewport}
            pending={catalog.isFetchingNextPage}
            onLoadMore={() => void catalog.fetchNextPage()}
          />
        {/if}
      {/if}
    </WorkspaceScroll>
  </div>
</div>

// src/pages/library/ui/library-workspace.tsx
import { useEffect, useState, type ReactNode } from "react";
import { Link, useElementScrollRestoration } from "@tanstack/react-router";
import { libraryCommandErrorMessage } from "@/entities/library";
import { formatCount } from "@/shared/lib/format";
import { useScrollTopOnChange } from "@/shared/lib/use-scroll-top-on-change";
import type { SortOption } from "@/shared/ui/collection-sort-control";
import { ScrollIndex } from "@/shared/ui/scroll-index";
import { WorkspaceScroll } from "@/shared/ui/workspace-scroll";
import {
  EmptyStatus,
  ErrorAlert,
  LoadMoreSentinel,
  LoadingStatus,
} from "@/shared/ui/workspace-status";
import type { LibrarySortDirection } from "@/shared/ipc";
import type { LibraryCatalogState } from "../model/use-library-catalog";
import { LibraryToolbar } from "./library-toolbar";

export type LibraryPresentationMeta = {
  title: string;
  singular: string;
  plural: string;
  searchLabel: string;
  searchPlaceholder: string;
};

export type LibraryScroll = {
  /** `null` until the scroll region has mounted. */
  viewport: HTMLDivElement | null;
  initialOffset: number | undefined;
  /** The list reports the index of its first visible item here (for the scroll index). */
  onTopIndexChange: (index: number) => void;
};

/**
 * The shell shared by every library presentation: toolbar, one scroll region, and
 * exactly one of loading, error, empty, or content. The presentation supplies
 * how its items are rendered.
 */
export function LibraryWorkspace<Item, Key extends string>({
  meta,
  scrollRestorationId,
  filter,
  onFilterChange,
  stateKey,
  sort,
  catalog,
  indexFor,
  children,
}: {
  meta: LibraryPresentationMeta;
  scrollRestorationId: string;
  filter: string;
  onFilterChange: (filter: string) => void;
  /** Changes when the filter or sort does, returning the list to the top. */
  stateKey: string;
  sort?: {
    key: Key;
    direction: LibrarySortDirection;
    options: readonly SortOption<Key>[];
    onKeyChange: (key: Key) => void;
    onToggleDirection: () => void;
  };
  catalog: LibraryCatalogState<Item>;
  /**
   * The index key of an item (a letter or a year) for the big label shown while scrolling.
   * The list must report its first visible item through `scroll.onTopIndexChange`.
   */
  indexFor?: (item: Item) => string;
  children: (items: Item[], scroll: LibraryScroll) => ReactNode;
}) {
  // State rather than a ref: descendants (the virtualizer) must re-render once the viewport exists.
  const [viewport, setViewport] = useState<HTMLDivElement | null>(null);
  const scrollEntry = useElementScrollRestoration({ id: scrollRestorationId });
  useScrollTopOnChange(viewport, stateKey);
  const { statusQuery, statusMessage, query, viewState } = catalog;
  const [topIndex, setTopIndex] = useState(0);
  const scrollIndex = useScrollIndex(
    viewport,
    topIndex,
    indexFor === undefined
      ? null
      : (i) => {
          const item = query.items[i];
          return item === undefined ? null : indexFor(item);
        },
  );

  return (
    <div className="grid h-full min-h-0 min-w-0 grid-rows-[auto_minmax(0,1fr)] overflow-hidden">
      <LibraryToolbar
        title={meta.title}
        countLabel={formatCount(query.totalCount, meta.singular, meta.plural)}
        searchLabel={meta.searchLabel}
        searchPlaceholder={meta.searchPlaceholder}
        filter={filter}
        updating={catalog.updating}
        onFilterChange={onFilterChange}
        sort={sort}
      />

      <div className="@container relative min-h-0">
        <ScrollIndex label={scrollIndex.label} visible={scrollIndex.visible} />
        <WorkspaceScroll
          scrollRestorationId={scrollRestorationId}
          viewportRef={setViewport}
          contentClassName="pt-6 pb-16"
        >
          {viewState === "loading" ? <LoadingStatus>Loading library…</LoadingStatus> : null}

          {viewState === "statusError" ? (
            <ErrorAlert
              message={libraryCommandErrorMessage(statusQuery.error)}
              onRetry={() => void statusQuery.refetch()}
            />
          ) : null}

          {viewState === "unavailable" ? <ErrorAlert message={statusMessage ?? ""} /> : null}

          {viewState === "catalogError" ? (
            <ErrorAlert
              message={libraryCommandErrorMessage(query.error)}
              onRetry={() => void query.refetch()}
            />
          ) : null}

          {viewState === "empty" ? (
            <EmptyStatus>
              {filter === "" ? (
                <>
                  No {meta.plural} in your library.{" "}
                  <Link to="/settings" className="text-foreground underline underline-offset-4">
                    Add a music folder
                  </Link>
                </>
              ) : (
                `No results for “${filter}”.`
              )}
            </EmptyStatus>
          ) : null}

          {viewState === "content" ? (
            <>
              {children(query.items, {
                viewport,
                initialOffset: scrollEntry?.scrollY,
                onTopIndexChange: setTopIndex,
              })}
              {query.hasNextPage ? (
                <LoadMoreSentinel
                  pending={query.isFetchingNextPage}
                  onLoadMore={() => void query.fetchNextPage()}
                />
              ) : null}
            </>
          ) : null}
        </WorkspaceScroll>
      </div>
    </div>
  );
}

/** How long the index stays after the last scroll. */
const INDEX_HOLD_MS = 800;

/**
 * The scroll index label for the item at `topIndex` (reported by the list itself, so nothing
 * is read back from the DOM), and whether the region is being scrolled: it shows while
 * scrolling and for a moment after.
 */
function useScrollIndex(
  viewport: HTMLElement | null,
  topIndex: number,
  labelAt: ((index: number) => string | null) | null,
) {
  const [visible, setVisible] = useState(false);
  const enabled = labelAt !== null;

  useEffect(() => {
    if (viewport === null || !enabled) return;
    let hold: ReturnType<typeof setTimeout> | undefined;
    const onScroll = () => {
      setVisible(true);
      clearTimeout(hold);
      hold = setTimeout(() => setVisible(false), INDEX_HOLD_MS);
    };
    viewport.addEventListener("scroll", onScroll, { passive: true });
    return () => {
      viewport.removeEventListener("scroll", onScroll);
      clearTimeout(hold);
    };
  }, [viewport, enabled]);

  return { label: labelAt?.(topIndex) ?? null, visible };
}
