// src/lib/components/queue-panel/queue-panel.svelte
<script lang="ts">
  import type { Attachment } from "svelte/attachments";
  import { getPlayback } from "$lib/playback/context";
  import { queuePanel } from "$lib/shell/queue-panel.svelte";
  import { Sheet, SheetContent, SheetHeader, SheetTitle } from "$lib/ui/shadcn/sheet";
  import QueueFooter from "./queue-footer.svelte";
  import QueueRow from "./queue-row.svelte";
  import { createShuffleCascade } from "./shuffle-cascade.svelte";
  import UpcomingList from "./upcoming-list.svelte";

  const playback = getPlayback();

  const queue = $derived(playback.queue);
  const history = $derived(queue?.history ?? []);
  const cascade = createShuffleCascade(
    () => playback.shuffleEnabled,
    () => queuePanel.isOpen,
  );

  let scrollElement = $state<HTMLDivElement | null>(null);
  let content = $state<HTMLDivElement | null>(null);

  // Opening the panel shows the current track at the top, with what was played above it.
  const showAtTop: Attachment<HTMLElement> = (node) => {
    node.scrollIntoView({ block: "start" });
  };
</script>

<!-- Not modal: the library stays visible and usable beside the queue, so there is no backdrop and
     a click elsewhere does not close it (Escape and the queue button do). -->
<Sheet
  open={queuePanel.isOpen}
  onOpenChange={(open) => (open ? queuePanel.open() : queuePanel.close())}
>
  <SheetContent
    side="right"
    class="w-80 gap-0 p-0"
    overlay={false}
    showCloseButton={false}
    interactOutsideBehavior="ignore"
    trapFocus={false}
    preventScroll={false}
  >
    <div class="border-b border-border">
      <SheetHeader>
        <SheetTitle>Queue</SheetTitle>
      </SheetHeader>
    </div>
    <div bind:this={scrollElement} class="min-h-0 flex-1 overflow-y-auto py-2">
      <div bind:this={content}>
        {#each history as item (item.id)}
          <QueueRow {item} tone="past" onPlay={() => void playback.playQueueItem(item.id)} />
        {/each}
        {#if queue?.current}
          <div {@attach showAtTop}>
            <QueueRow item={queue.current} tone="current" />
          </div>
        {:else}
          <p class="px-4 py-6 text-sm text-muted-foreground">Nothing playing.</p>
        {/if}
        {#if queue && queue.upcomingCount > 0}
          <UpcomingList {scrollElement} {content} cascading={cascade.current} />
        {/if}
      </div>
    </div>
    <QueueFooter />
  </SheetContent>
</Sheet>

// src/widgets/queue-panel/ui/queue-panel.tsx
import { useLayoutEffect, useRef, useState } from "react";
import { usePlaybackActions, usePlaybackQueue } from "@/entities/playback";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/shared/ui/shadcn/sheet";
import { useQueuePanel } from "@/features/toggle-queue-panel";
import { useShuffleCascade } from "../model/use-shuffle-cascade";
import { QueueFooter } from "./queue-footer";
import { QueueRow } from "./queue-row";
import { UpcomingList } from "./upcoming-list";

/** A 320px Acrylic panel from the right: what was played, the current track, and what is next. */
export function QueuePanel() {
  const { isOpen, close } = useQueuePanel();
  const { queue, shuffleEnabled } = usePlaybackQueue();
  const playback = usePlaybackActions();
  const [scrollElement, setScrollElement] = useState<HTMLDivElement | null>(null);
  const cascading = useShuffleCascade(shuffleEnabled, isOpen);
  const history = queue?.history ?? [];
  // Opening the panel shows the current track at the top, with what was played above it.
  const currentRow = useRef<HTMLDivElement>(null);
  useLayoutEffect(() => {
    currentRow.current?.scrollIntoView({ block: "start" });
  }, [scrollElement]);

  return (
    // Not modal: the library stays visible and usable beside the queue, so there is no backdrop
    // and a click elsewhere does not close it (Escape and the queue button do).
    <Sheet
      open={isOpen}
      modal={false}
      disablePointerDismissal
      onOpenChange={(open) => (open ? undefined : close())}
    >
      <SheetContent side="right" overlay={false} className="w-80 gap-0 p-0" aria-label="Queue">
        <SheetHeader className="border-b border-border pb-4">
          <SheetTitle>Queue</SheetTitle>
        </SheetHeader>
        <div ref={setScrollElement} className="min-h-0 flex-1 overflow-y-auto py-2">
          {history.map((item) => (
            <QueueRow
              key={item.id}
              item={item}
              tone="past"
              onPlay={() => void playback.playQueueItem(item.id)}
            />
          ))}
          {queue?.current ? (
            <div ref={currentRow}>
              <QueueRow item={queue.current} tone="current" />
            </div>
          ) : (
            <p className="px-4 py-6 text-sm text-muted-foreground">Nothing playing.</p>
          )}
          {queue && queue.upcomingCount > 0 ? (
            <UpcomingList scrollElement={scrollElement} cascading={cascading} />
          ) : null}
        </div>
        <QueueFooter />
      </SheetContent>
    </Sheet>
  );
}
