// src/lib/components/queue-panel/upcoming-list.svelte
<script lang="ts">
  import { flip } from "svelte/animate";
  import { getMotionBudget } from "$lib/shell/motion-budget.svelte";
  import { getPlayback } from "$lib/playback/context";
  import { createUpcomingItems } from "$lib/playback/upcoming-items.svelte";
  import { motionFor } from "$lib/ui/motion/svelte-motion";
  import { createVirtualRows } from "$lib/ui/virtual-rows.svelte";
  import { cn } from "$lib/utils/cn.js";
  import { QueueDrag } from "./queue-drag.svelte";
  import QueueRow, { QUEUE_ROW_PX } from "./queue-row.svelte";

  const CASCADE_STEP_MS = 15;
  const CASCADE_ROWS = 12;

  let {
    scrollElement,
    content,
    cascading,
  }: {
    /** The region the list scrolls in. */
    scrollElement: HTMLElement | null;
    /** Everything inside that region; its size changes move the list. */
    content: HTMLElement | null;
    /** Rows settle top to bottom instead of all at once (right after shuffle changes). */
    cascading: boolean;
  } = $props();

  const playback = getPlayback();

  const upcomingCount = $derived(playback.queue?.upcomingCount ?? 0);
  let list = $state<HTMLUListElement | null>(null);

  const queueDrag = new QueueDrag({
    onMove: (id, to) => void playback.moveQueueItem(id, to),
    rowHeight: QUEUE_ROW_PX,
    count: () => upcomingCount,
    scrollElement: () => scrollElement,
    list: () => list,
  });
  const drag = $derived(queueDrag.drag);

  const virtual = createVirtualRows({
    count: () => upcomingCount,
    scrollElement: () => scrollElement,
    rowHeight: QUEUE_ROW_PX,
    overscan: 8,
    initialOffset: () => 0,
    container: () => content,
    body: () => list,
  });

  const firstRow = $derived(virtual.items[0]?.index);
  const lastRow = $derived(virtual.items.at(-1)?.index);
  const itemAt = createUpcomingItems(playback, () =>
    firstRow === undefined || lastRow === undefined ? null : { start: firstRow, end: lastRow },
  );
  // Beyond what the snapshot carries, a row waits for its chunk to arrive.
  const rows = $derived(
    virtual.items.map(({ index }) => {
      const item = itemAt.at(index);
      return { index, item, key: item?.id ?? `waiting-${index}` };
    }),
  );

  const budget = getMotionBudget();
  const reduced = $derived(budget.current === "reduced");
  const motion = $derived(motionFor("mediumMove", reduced));

  /** Which edge of row `index` shows the drop line for insertion `slot`, if any. */
  function dropMarker(slot: number | null, index: number): "before" | "after" | undefined {
    if (slot === null) return undefined;
    if (slot === index) return "before";
    if (slot === upcomingCount && index === upcomingCount - 1) return "after";
    return undefined;
  }
</script>

<ul
  bind:this={list}
  style:padding-top="{virtual.topSpacer}px"
  style:padding-bottom="{virtual.bottomSpacer}px"
>
  {#each rows as { index, item, key } (key)}
    {@const dragging = item !== undefined && drag?.id === item.id}
    <li
      animate:flip={{
        duration: reduced ? 0 : motion.duration,
        easing: motion.easing,
        delay: cascading ? Math.min(index, CASCADE_ROWS) * CASCADE_STEP_MS : 0,
      }}
      aria-hidden={item === undefined ? "true" : undefined}
      class={cn(
        "relative transition-[translate,rotate,scale]",
        reduced && "transition-none",
        dragging && "z-10 rounded-lg bg-popover shadow-floating",
      )}
      style:height="{QUEUE_ROW_PX}px"
      style:translate={drag !== null && !dragging && index >= drag.slot
        ? `0 ${queueDrag.rowHeight}px`
        : undefined}
      style:rotate={dragging && !reduced ? "1deg" : undefined}
      style:scale={dragging && !reduced ? "1.02" : undefined}
      style:--drop-shift="{queueDrag.rowHeight}px"
      data-dragging={dragging ? "true" : undefined}
      data-drop={dropMarker(drag?.slot ?? null, index)}
    >
      {#if item !== undefined}
        <QueueRow
          {item}
          tone="upcoming"
          dragHandlers={queueDrag.handlersFor(item.id, index)}
          onMoveEarlier={() => void playback.moveQueueItem(item.id, index - 1)}
          onMoveLater={() => void playback.moveQueueItem(item.id, index + 1)}
          canMoveEarlier={index > 0}
          canMoveLater={index < upcomingCount - 1}
          onPlay={() => void playback.playQueueItem(item.id)}
          onRemove={() => void playback.removeQueueItem(item.id)}
        />
      {/if}
    </li>
  {/each}
</ul>

// src/widgets/queue-panel/ui/upcoming-list.tsx
import { useLayoutEffect, useMemo, useState, type CSSProperties } from "react";
import { m } from "motion/react";
import { useVirtualizer } from "@tanstack/react-virtual";
import { usePlaybackActions, usePlaybackQueue, useUpcomingItems } from "@/entities/playback";
import { cn } from "@/shared/lib/utils";
import { useMotionTransition } from "@/shared/ui/motion";
import { useQueueDrag } from "../model/use-queue-drag";
import { QUEUE_ROW_PX, QueueRow } from "./queue-row";

const CASCADE_STEP_S = 0.015;

/**
 * The upcoming tracks, which can be as long as the library: only the rows near the view are
 * mounted. Rows reorder by dragging their handle to any position (`moveQueueItem` takes the
 * target index), or one step at a time with the buttons.
 */
export function UpcomingList({
  scrollElement,
  cascading,
}: {
  scrollElement: HTMLDivElement | null;
  /** Rows settle top to bottom instead of all at once (right after shuffle changes). */
  cascading: boolean;
}) {
  const { queue } = usePlaybackQueue();
  const playback = usePlaybackActions();
  const upcomingCount = queue?.upcomingCount ?? 0;
  const hasCurrent = queue?.current != null;
  const historyLength = queue?.history.length ?? 0;
  const { listRef, drag, handlersFor } = useQueueDrag(
    (id, to) => void playback.moveQueueItem(id, to),
    QUEUE_ROW_PX,
    upcomingCount,
    scrollElement,
  );
  const [listOffset, setListOffset] = useState(0);
  useLayoutEffect(() => {
    const list = listRef.current;
    if (scrollElement === null || list === null) return;
    setListOffset(
      list.getBoundingClientRect().top -
        scrollElement.getBoundingClientRect().top +
        scrollElement.scrollTop -
        parseFloat(getComputedStyle(list).paddingTop),
    );
  }, [scrollElement, hasCurrent, listRef, historyLength]);
  const virtualizer = useVirtualizer({
    count: upcomingCount,
    getScrollElement: () => scrollElement,
    estimateSize: () => QUEUE_ROW_PX,
    overscan: 8,
    scrollMargin: listOffset,
  });
  const virtualRows = virtualizer.getVirtualItems();
  const firstRow = virtualRows[0]?.index;
  const lastRow = virtualRows.at(-1)?.index;
  const itemAt = useUpcomingItems(
    useMemo(
      () =>
        firstRow === undefined || lastRow === undefined ? null : { start: firstRow, end: lastRow },
      [firstRow, lastRow],
    ),
  );
  const rowTransition = useMotionTransition("mediumMove");

  return (
    <ul
      ref={listRef}
      style={{
        paddingTop: virtualRows[0] ? virtualRows[0].start - listOffset : 0,
        paddingBottom: virtualRows.length
          ? virtualizer.getTotalSize() - (virtualRows.at(-1)!.end - listOffset)
          : 0,
      }}
    >
      {virtualRows.map(({ index }) => {
        const item = itemAt(index);
        // Beyond what the snapshot carries, a row waits for its chunk to arrive.
        if (item === undefined) {
          return <li key={`waiting-${index}`} aria-hidden="true" className="h-14" />;
        }
        return (
          <m.li
            key={item.id}
            layout="position"
            animate={{
              // The dragged row lifts; rows at and after the drop slot make room.
              y: drag !== null && drag.id !== item.id && index >= drag.slot ? drag.rowHeight : 0,
              rotate: drag?.id === item.id ? 1 : 0,
              scale: drag?.id === item.id ? 1.02 : 1,
            }}
            transition={
              cascading
                ? { ...rowTransition, delay: Math.min(index, 12) * CASCADE_STEP_S }
                : rowTransition
            }
            className={cn(
              "relative",
              drag?.id === item.id && "z-10 rounded-lg bg-popover shadow-floating",
            )}
            style={{ "--drop-shift": `${drag?.rowHeight ?? 0}px` } as CSSProperties}
            data-dragging={drag?.id === item.id ? "true" : undefined}
            data-drop={dropMarker(drag?.slot ?? null, index, upcomingCount)}
          >
            <QueueRow
              item={item}
              tone="upcoming"
              dragHandlers={handlersFor(item.id, index)}
              onMoveEarlier={() => void playback.moveQueueItem(item.id, index - 1)}
              onMoveLater={() => void playback.moveQueueItem(item.id, index + 1)}
              canMoveEarlier={index > 0}
              canMoveLater={index < upcomingCount - 1}
              onPlay={() => void playback.playQueueItem(item.id)}
              onRemove={() => void playback.removeQueueItem(item.id)}
            />
          </m.li>
        );
      })}
    </ul>
  );
}

/** Which edge of row `index` shows the drop line for insertion `slot`, if any. */
function dropMarker(slot: number | null, index: number, count: number) {
  if (slot === null) return undefined;
  if (slot === index) return "before";
  if (slot === count && index === count - 1) return "after";
  return undefined;
}
