// src/lib/ui/shadcn/slider/slider.svelte
<script lang="ts">
	import { Slider as SliderPrimitive } from "bits-ui";
	import { cn, type WithoutChildrenOrChild } from "$lib/utils/cn.js";

	let {
		ref = $bindable(null),
		value = $bindable(),
		orientation = "horizontal",
		class: className,
		thumbProps,
		...restProps
	}: WithoutChildrenOrChild<SliderPrimitive.RootProps> & {
		/** Attributes for each thumb, which is the element that carries role=slider (aria-label, aria-valuetext). */
		thumbProps?: Record<string, string | undefined>;
	} = $props();
</script>

<!--
Discriminated Unions + Destructing (required for bindable) do not
get along, so we shut typescript up by casting `value` to `never`.
-->
<SliderPrimitive.Root
	bind:ref
	bind:value={value as never}
	data-slot="slider"
	{orientation}
	class={cn(
		"data-vertical:min-h-40 relative flex w-full touch-none items-center select-none data-disabled:opacity-50 data-vertical:h-full data-vertical:w-auto data-vertical:flex-col",
		className
	)}
	{...restProps}
>
	{#snippet children({ thumbItems })}
		<span
			data-slot="slider-track"
			data-orientation={orientation}
			class={cn(
				"bg-muted rounded-full data-horizontal:h-1 data-horizontal:w-full data-vertical:h-full data-vertical:w-1 relative grow overflow-hidden data-horizontal:w-full data-vertical:h-full"
			)}
		>
			<SliderPrimitive.Range
				data-slot="slider-range"
				class={cn(
					"bg-primary absolute select-none data-horizontal:h-full data-vertical:w-full"
				)}
			/>
		</span>
		{#each thumbItems as thumb (thumb.index)}
			<SliderPrimitive.Thumb
				data-slot="slider-thumb"
				index={thumb.index}
				{...thumbProps}
				class="border-ring ring-ring/50 relative size-3 rounded-full border bg-white transition-[color,box-shadow] after:absolute after:-inset-2 hover:ring-3 focus-visible:ring-3 focus-visible:outline-hidden active:ring-3 block shrink-0 select-none disabled:pointer-events-none disabled:opacity-50"
			/>
		{/each}
	{/snippet}
</SliderPrimitive.Root>

// src/components/ui/slider.tsx
import { Slider as SliderPrimitive } from "@base-ui/react/slider";
import type { ComponentProps } from "react";
export type SliderAppearance = "default" | "subdued" | "idle" | "pending";

export function Slider({
  appearance = "default",
  "aria-label": ariaLabel,
  "aria-valuetext": ariaValueText,
  value,
  defaultValue,
  ...props
}: Omit<ComponentProps<typeof SliderPrimitive.Root>, "className"> & {
  "aria-label": string;
  "aria-valuetext"?: string;
  appearance?: SliderAppearance;
}) {
  const values = Array.isArray(value)
    ? value
    : Array.isArray(defaultValue)
      ? defaultValue
      : [value];
  const pending = appearance === "pending";
  const subdued = appearance === "subdued";
  const idle = appearance === "idle";
  return (
    <SliderPrimitive.Root
      {...props}
      value={value}
      defaultValue={defaultValue}
      data-slot="slider"
      thumbAlignment="edge"
      className={`w-full min-w-0 ${idle ? "opacity-[.55]" : pending ? "opacity-100" : "data-[disabled]:opacity-70"}`}
    >
      <SliderPrimitive.Control className="group/slider-control relative flex min-h-10 w-full min-w-0 touch-none select-none items-center forced-colors:outline forced-colors:outline-ButtonText">
        <SliderPrimitive.Track
          data-slot="slider-track"
          className={`relative h-1 min-w-0 flex-1 overflow-hidden rounded-full transition-colors duration-[var(--effect-feedback)] ease-interface ${subdued ? "bg-border-control" : pending ? "bg-text-secondary" : "bg-border-control"} group-hover/slider-control:bg-text-secondary group-data-[disabled]/slider-control:bg-surface-pressed forced-colors:bg-[CanvasText] forced-colors:opacity-[.35]`}
        >
          <SliderPrimitive.Indicator
            data-slot="slider-range"
            className={`h-full transition-colors duration-[var(--effect-state)] ease-interface ${subdued ? "bg-text-muted" : "bg-text-primary"} group-data-[disabled]/slider-control:bg-text-disabled ${pending ? "group-data-[disabled]/slider-control:bg-text-primary" : ""} forced-colors:bg-[Highlight]`}
          />
        </SliderPrimitive.Track>
        {values.map((_, index) => (
          <SliderPrimitive.Thumb
            key={index}
            index={index}
            data-slot="slider-thumb"
            className={`block h-4 w-4 flex-none rounded-full border-0 transition-colors duration-[var(--effect-state)] ease-interface focus-visible:outline-2 focus-visible:outline-focus-ring focus-visible:outline-offset-2 ${subdued ? "bg-text-muted" : "bg-text-primary"} group-data-[disabled]/slider-control:bg-text-disabled ${pending ? "group-data-[disabled]/slider-control:bg-text-primary" : ""} forced-colors:bg-[Highlight] forced-colors:focus-visible:outline-[Highlight]`}
            getAriaLabel={() => ariaLabel}
            aria-valuetext={ariaValueText}
          />
        ))}
      </SliderPrimitive.Control>
    </SliderPrimitive.Root>
  );
}
